-- Respirators seed inserts (batch 1 of N)
-- Schema reference: docs/prodtableshcema.json
-- Images: placeholders applied to image_url and image2_url
-- Related products applied to all rows

begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 1) BLS Zer032 Active (Disposable mask)
(
  'BLS Zer032 Active',
  'FFP3 cup shaped filtering facepieces with Active Shield electronic valve',
  'FFP3 cup shaped filtering facepieces with Active Shield electronic valve',
  'Respiratory protection',
  'Disposable masks',
  array[
    'Smart breathing valve (Narvalo Active Shield) with adaptive fan to enhance comfort and lithium battery',
    'External protective layer against dirt, dust, and liquids',
    'Nano filtration (tested down to 0.001 micron)',
    'Usage and safety monitoring via IoT',
    'Anatomical mask',
    'High comfort thanks to soft gasket ensuring fit on all face shapes',
    'Internal nose clip',
    'Adjustable straps'
  ],
  array[
    'Protection against medicines and active pharmaceutical ingredients in pharmaceutical and laboratory environments',
    'Protection against dusts and particles in construction',
    'Protection during sanding activities',
    'Protection against emulsions of fertilizers or other chemical or biological agents'
  ],
  array['Pharmaceutical','research','construction','automotive','manufacturing','agriculture'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":["disposable mask","smart","IoT","FFP3"],"it":["mascherina monouso","smart","IoT","FFP3"]}'::jsonb,
  '{"en":"BLS Zer032 Active","it":"BLS Zer032 Active"}'::jsonb,
  '{"en":"FFP3 cup shaped filtering facepieces with Active Shield electronic valve","it":"Facciali filtranti FFP3 a coppa con valvola elettronica Active Shield"}'::jsonb,
  '{"en":"FFP3 cup shaped filtering facepieces with Active Shield electronic valve","it":"Facciali filtranti FFP3 a coppa con valvola elettronica Active Shield"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Disposable masks","it":"Mascherine monouso"}'::jsonb,
  '{"en":"Universal","it":"Unica"}'::jsonb,
  '{"en":["Polypropylene (PP)","Polyethylene (PE)","Other"],"it":["Polipropilene (PP)","Polietilene (PE)","Altro"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  'FFP3',
  '50',
  null,
  null,
  null,
  null,
  '8101070',
  '{"en149":{"enabled":true,"class":"FFP3","nr":false,"r":true,"d":true}}'::jsonb
),
-- 2) BLS Zer032 C Active (Disposable mask with carbon layer)
(
  'BLS Zer032 C Active',
  'FFP3 cup shaped filtering facepieces with Active Shield electronic valve and active carbon layer',
  'FFP3 cup shaped filtering facepieces with Active Shield electronic valve',
  'Respiratory protection',
  'Disposable masks',
  array[
    'Smart breathing valve (Narvalo Active Shield) with adaptive fan to enhance comfort and lithium battery. Usage and safety monitoring via IoT.',
    'Activated carbon layer to remove unpleasant odours',
    'External protective layer against dirt, dust, and liquids',
    'Nano filtration (tested down to 0.001 micron)',
    'Anatomical mask',
    'High comfort thanks to soft gasket ensuring fit on all face shapes',
    'Internal nose clip',
    'Adjustable straps'
  ],
  array[
    'Protection against medicines and active pharmaceutical ingredients in pharmaceutical and laboratory environments',
    'Protection against dusts and particles in construction',
    'Protection during sanding activities',
    'Protection against emulsions of fertilizers or other chemical or biological agents'
  ],
  array['Pharmaceutical','research','construction','automotive','manufacturing','agriculture'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":["disposable mask","smart","IoT","FFP3"],"it":["mascherina monouso","smart","IoT","FFP3"]}'::jsonb,
  '{"en":"BLS Zer032 C Active","it":"BLS Zer032 C Active"}'::jsonb,
  '{"en":"FFP3 cup shaped filtering facepieces with Active Shield electronic valve and active carbon layer","it":"Facciali filtranti FFP3 a coppa con valvola elettronica Active Shield e strato di Carboni Attivi"}'::jsonb,
  '{"en":"FFP3 cup shaped filtering facepieces with Active Shield electronic valve","it":"Facciali filtranti FFP3 a coppa con valvola elettronica Active Shield"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Disposable masks","it":"Mascherine monouso"}'::jsonb,
  '{"en":"Universal","it":"Unica"}'::jsonb,
  '{"en":["Polypropylene (PP)","Polyethylene (PE)","Other"],"it":["Polipropilene (PP)","Polietilene (PE)","Altro"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  'FFP3',
  '50',
  null,
  null,
  null,
  null,
  '8101071',
  '{"en149":{"enabled":true,"class":"FFP3","nr":false,"r":true,"d":true}}'::jsonb
),
-- 3) BLS 5600 (Full-face mask, B-Lock)
(
  'BLS 5600',
  'Full-face masks with thermoplastic rubber face seal and B-lock bayonet connection. Compatible with the BLS 200 filter range, for protection against gases/vapors and toxic particulates',
  'Full-face mask with b-lock connection',
  'Respiratory protection',
  'Full face masks',
  array[
    'Scratch resistant visor (Live visor), optical class 1 (EN166)',
    'Wide range of spare parts to extend use and lifespan of the mask',
    '6-point harness for precise adjustment and pressure distribution on the face',
    'Anallergic',
    'Thermoplastic face seal for added comfort',
    'Anti-fog visor'
  ],
  array[
    'Protection against aerial contaminants and particles combined with eye protection',
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":["full-face mask","B-Lock"],"it":["maschera intera facciale","B-lock"]}'::jsonb,
  '{"en":"BLS 5600","it":"BLS 5600"}'::jsonb,
  '{"en":"Full-face masks with thermoplastic rubber face seal and B-lock bayonet connection. Compatible with the BLS 200 filter range, for protection against gases/vapors and toxic particulates","it":"Maschere intera con guarnizione facciale in gomma termoplastica e raccordo a baionetta b-lock. Compatibili con la gamma di filtri BLS 200, per protezione da gas/vapori e particolati tossici"}'::jsonb,
  '{"en":"Full-face mask with b-lock connection","it":"Maschera intera facciale con connessione a baionetta b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Full face masks","it":"Maschere integrali"}'::jsonb,
  '{"en":"S - M - L","it":"S - M - L"}'::jsonb,
  '{"en":["Thermoplasticelastomer (TPE)","Polycarbonate (PC)","Other"],"it":["Elastomero termoplastico (TPE)","Policarbonato (PC)","Altro"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  'Class 1',
  '1000 (Dust), 2000 (Gas filters)',
  array['B-Lock'],
  array['BLS 200 Filters','BLS 201 Filters'],
  null,
  null,
  '8001083',
  '{"en166":{"enabled":true,"class":"1"},"en136":{"enabled":true,"class":"Class 2"}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 13 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- BLS 430 (Combined, Universal RD40)
(
  'BLS 430',
  'Combined filter with universal RD40 connection for full masks',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartridges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapour, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 430","it":"BLS 430"}'::jsonb,
  '{"en":"Combined filter with universal RD40 connection for full masks","it":"Filtro combinato con aggancio universale RD40 per maschere facciali integrali"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartridges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["Aluminium with plastic caps","Pleated fibre mesh","Activated carbons grains"],"it":["Alluminio con copertura in plastica","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Full masks'],
  'Combined',
  array['Reaktor A2P3 R D'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"din_3181_3":{"enabled":true}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 12 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 34) BLS 441 (Combined, Universal RD40)
(
  'BLS 441',
  'Dust filter with universal RD40 connection and activated carbons',
  'Dust filter with universal RD40 connection and activated carbons',
  'Respiratory protection',
  'Filters, Cartridges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices',
    'Aluminium casing to ensure mechanical and heat resistence'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 441","it":"BLS 441"}'::jsonb,
  '{"en":"Dust filter with universal RD40 connection and activated carbons","it":"Filtro per Polveri con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Dust filter with universal RD40 connection and activated carbons","it":"Filtro per Polveri con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartridges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["Alluminium with plastic caps","Pleated fiber mesh","Activated carbons grains"],"it":["Alluminio con copertura in plastica","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Full masks'],
  'Combined',
  array['Reaktor A2P3 R D'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"din_3181_3":{"enabled":true}}'::jsonb
),
-- 35) BLS 442 (Combined, Universal RD40)
(
  'BLS 442',
  'Gasses & Vapours filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartridges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices',
    'Aluminium casing to ensure mechanical and heat resistence'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 442","it":"BLS 442"}'::jsonb,
  '{"en":"Gasses & Vapours filter with universal RD40 connection and activated carbons","it":"Filtro per Gas & Vapori con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartridges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["Alluminium with plastic caps","Pleated fiber mesh","Activated carbons grains"],"it":["Alluminio con copertura in plastica","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Full masks'],
  'Combined',
  array['Reaktor A2P3 R D'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"din_3181_3":{"enabled":true}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 11 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 31) BLS 423 (Combined ABE2P3 R, Universal RD40)
(
  'BLS 423',
  'Combined filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 423","it":"BLS 423"}'::jsonb,
  '{"en":"Combined filter with universal RD40 connection and activated carbons","it":"Filtro combinato con attacco universale RD40 per maschere facciali integrali"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Full masks'],
  'Combined',
  array['ABE2P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true,"b":true,"e":true}}}'::jsonb
),
-- 32) BLS 424 (Combined ABEK1P3 R, Universal RD40)
(
  'BLS 424',
  'Combined filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 424","it":"BLS 424"}'::jsonb,
  '{"en":"Combined filter with universal RD40 connection and activated carbons","it":"Filtro combinato con attacco universale RD40 per maschere facciali integrali"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartridges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Full masks'],
  'Combined',
  array['ABEK1P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 1","gases":{"a":true,"b":true,"e":true,"k":true}}}'::jsonb
),
-- 33) BLS 425 (Combined ABEK2HgP3 R (NO/CO), Universal RD40)
(
  'BLS 425',
  'Combined filter with universal RD40 connection and activated carbons',
  'Combined filter with universal RD40 connection and activated carbons.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 425","it":"BLS 425"}'::jsonb,
  '{"en":"Combined filter with universal RD40 connection and activated carbons","it":"Filtro combinato con attacco universale RD40 per maschere facciali integrali"}'::jsonb,
  '{"en":"Combined filter with universal RD40 connection and activated carbons.","it":"Filtro combinato con attacco universale RD40 per maschere facciali integrali"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["Alluminium with plastic caps","Pleated fiber mesh","Activated carbons grains"],"it":["Alluminio con copertura in plastica","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Full masks'],
  'Combined',
  array['ABEK2HgNOCO20P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true,"b":true,"e":true,"k":true,"hg":true,"no":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 10 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 28) BLS 415 (Gasses & Vapours ABEK2, Universal RD40)
(
  'BLS 415',
  'Gasses & Vapours filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 415","it":"BLS 415"}'::jsonb,
  '{"en":"Gasses & Vapours filter with universal RD40 connection and activated carbons","it":"Filtro per Gas & Vapori con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['ABEK2'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true,"b":true,"e":true,"k":true}}}'::jsonb
),
-- 29) BLS 421 (Combined A2P3 R, Universal RD40)
(
  'BLS 421',
  'Combined filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 421","it":"BLS 421"}'::jsonb,
  '{"en":"Combined filter with universal RD40 connection and activated carbons","it":"Filtro combinato con attacco universale RD40 b-lock e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Combined',
  array['A2P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true}}}'::jsonb
),
-- 30) BLS 422 (Combined AXP3 NR, Universal RD40)
(
  'BLS 422',
  'Combined filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 422","it":"BLS 422"}'::jsonb,
  '{"en":"Combined filter with universal RD40 connection and activated carbons","it":"Filtro combinato con attacco universale RD40 b-lock e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Combined',
  array['AXP3 NR'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":false},"en14387":{"enabled":true,"class":"Class 1","gases":{"ax":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 9 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 25) BLS 412 (Gasses & Vapours AX, Universal RD40)
(
  'BLS 412',
  'Gasses & Vapours filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 412","it":"BLS 412"}'::jsonb,
  '{"en":"Gasses & Vapours filter with universal RD40 connection and activated carbons","it":"Filtro per Gas & Vapori con attacco universale RD40 b-lock e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['AX'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 1","gases":{"ax":true}}}'::jsonb
),
-- 26) BLS 413 (Gasses & Vapours K2, Universal RD40)
(
  'BLS 413',
  'Gasses & Vapours filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 413","it":"BLS 413"}'::jsonb,
  '{"en":"Gasses & Vapours filter with universal RD40 connection and activated carbons","it":"Filtro per Gas & Vapori con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['K2'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 2","gases":{"k":true}}}'::jsonb
),
-- 27) BLS 414 (Gasses & Vapours ABE2, Universal RD40)
(
  'BLS 414',
  'Gasses & Vapours filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 414","it":"BLS 414"}'::jsonb,
  '{"en":"Gasses & Vapours filter with universal RD40 connection and activated carbons","it":"Filtro per Gas & Vapori con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['ABE2'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true,"b":true,"e":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 8 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 22) BLS 254 (Combined ABEK2HgP3 R, B-Lock)
(
  'BLS 254',
  'Combined filter with b-lock connection and activated carbons',
  'Combined filter with b-lock connection and activated carbons.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 254","it":"BLS 254"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons.","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Combined',
  array['ABEK2HgP3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true,"b":true,"e":true,"k":true,"hg":true}}}'::jsonb
),
-- 23) BLS 401 (Dust P3 R, Universal RD40)
(
  'BLS 401',
  'Gasses & Vapours filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister allows control over the compression of the activated carbons within',
    'Dust filtering efficiency 99.99%'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 401","it":"BLS 401"}'::jsonb,
  '{"en":"Gasses & Vapours filter with universal RD40 connection and activated carbons","it":"Filtro per Gas & Vapori con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Dust',
  array['P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true}}'::jsonb
),
-- 24) BLS 411 (Gasses & Vapours A2, Universal RD40)
(
  'BLS 411',
  'Gasses & Vapours filter with universal RD40 connection and activated carbons',
  'Universal RD40 filter',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Standard thread connection according to EN 148-1, universal across all respiratory protection devices'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 411","it":"BLS 411"}'::jsonb,
  '{"en":"Gasses & Vapours filter with universal RD40 connection and activated carbons","it":"Filtro per Gas & Vapori con attacco universale RD40 e carboni attivi"}'::jsonb,
  '{"en":"Universal RD40 filter","it":"Filtro con aggancio universale RD40"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated fiber mesh","Activated carbons grains"],"it":["ABS","rete a fibre plissettate","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['Universal (RD40)'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['A2'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 7 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 19) BLS 243 (Gasses & Vapours ABEK2, B-Lock)
(
  'BLS 243',
  'Gasses & Vapours filter with b-lock connection and activated carbons. Tested on formaldehyde',
  'Gasses & Vapours filter with b-lock connection and activated carbons.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons',
    'Tested on formaldehyde'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 243","it":"BLS 243"}'::jsonb,
  '{"en":"\"Gasses & Vapours filter with b-lock connection and activated carbons.\\nTested on formaldehyde\"","it":"\"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi.\\nTestato con formaldeide\""}'::jsonb,
  '{"en":"Gasses & Vapours filter with b-lock connection and activated carbons.","it":"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['ABEK2'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true,"b":true,"e":true,"k":true}}}'::jsonb
),
-- 20) BLS 244 (Gasses & Vapours K2, B-Lock)
(
  'BLS 244',
  'Gasses & Vapours filter with b-lock connection and activated carbons. Tested on formaldehyde',
  'Gasses & Vapours filter with b-lock connection and activated carbons.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons',
    'Tested on formaldehyde'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 244","it":"BLS 244"}'::jsonb,
  '{"en":"\"Gasses & Vapours filter with b-lock connection and activated carbons.\\nTested on formaldehyde\"","it":"\"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi.\\nTestato con formaldeide\""}'::jsonb,
  '{"en":"Gasses & Vapours filter with b-lock connection and activated carbons.","it":"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['K2'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 2","gases":{"k":true}}}'::jsonb
),
-- 21) BLS 253 (Combined ABE2P3 R, B-Lock)
(
  'BLS 253',
  'Combined filter with b-lock connection and activated carbons',
  'Combined filter with b-lock connection and activated carbons.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 253","it":"BLS 253"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons.","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Combined',
  array['ABE2P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true,"b":true,"e":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 6 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 16) BLS 226 (Combined ABE1P3 R, B-Lock)
(
  'BLS 226',
  'Combined filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 226","it":"BLS 226"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Combined',
  array['ABE1P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"gases":{"a":true,"b":true,"e":true}}}'::jsonb
),
-- 17) BLS 227 (Combined ABEK1HgP3, B-Lock)
(
  'BLS 227',
  'Combined filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 227","it":"BLS 227"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Combined',
  array['ABEK1HgP3'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"gases":{"a":true,"b":true,"e":true,"k":true,"hg":true}}}'::jsonb
),
-- 18) BLS 242 (Gasses & Vapours ABE2, B-Lock)
(
  'BLS 242',
  'Gasses & Vapours filter with b-lock connection and activated carbons. Tested on Fluoridric acid',
  'Combined filter with b-lock connection and activated carbons.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons',
    'Tested on Fluoridric acid'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 242","it":"BLS 242"}'::jsonb,
  '{"en":"\"Combined filter with b-lock connection and activated carbons.\\nTested on Fluoridric acid\"","it":"\"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi.\\nTestato con acido fluoridrico\""}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['ABE2'],
  null,
  '{"en14387":{"enabled":true,"gases":{"a":true,"b":true,"e":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 5 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 13) BLS 221 (Combined A2P3 R, B-Lock)
(
  'BLS 221',
  'Combined filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 221","it":"BLS 221"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Combined',
  array['A2P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true}}}'::jsonb
),
-- 14) BLS 222 (Combined ABEK1P3 R, B-Lock)
(
  'BLS 222',
  'Combined filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 222","it":"BLS 222"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Combined',
  array['ABEK1P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true},"en14387":{"enabled":true,"class":"Class 1","gases":{"a":true,"b":true,"e":true,"k":true}}}'::jsonb
),
-- 15) BLS 225 (Combined AXP3 NR, B-Lock)
(
  'BLS 225',
  'Combined filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 225","it":"BLS 225"}'::jsonb,
  '{"en":"Combined filter with b-lock connection and activated carbons","it":"Filtro per Combinati con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Combined',
  array['AXP3 NR'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":false},"en14387":{"enabled":true,"class":"Class 1","gases":{"ax":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 4 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 10) BLS 212 (Gasses & Vapours filter, B-Lock, AX)
(
  'BLS 212',
  'Gasses & Vapours filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 212","it":"BLS 212"}'::jsonb,
  '{"en":"Gasses & Vapours filter with b-lock connection and activated carbons","it":"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['AX'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 1","gases":{"ax":true}}}'::jsonb
),
-- 11) BLS 213 (Gasses & Vapours filter, B-Lock, ABE1)
(
  'BLS 213',
  'Gasses & Vapours filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 213","it":"BLS 213"}'::jsonb,
  '{"en":"Gasses & Vapours filter with b-lock connection and activated carbons","it":"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['ABE1'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 1","gases":{"a":true,"b":true,"e":true}}}'::jsonb
),
-- 12) BLS 214 (Gasses & Vapours filter, B-Lock, ABEK1)
(
  'BLS 214',
  'Gasses & Vapours filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 214","it":"BLS 214"}'::jsonb,
  '{"en":"Gasses & Vapours filter with b-lock connection and activated carbons","it":"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['ABEK1'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 1","gases":{"a":true,"b":true,"e":true,"k":true}}}'::jsonb
);

commit;

-- Respirators seed inserts (batch 3 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 7) BLS 202 (Dust filter, B-Lock)
(
  'BLS 202',
  'Dust filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Dust filtering efficiency 99.99%'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 202","it":"BLS 202"}'::jsonb,
  '{"en":"Dust filter with b-lock connection and activated carbons","it":"Filtro per Polveri con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Dust',
  array['P3 R'],
  null,
  '{"en143":{"enabled":true,"class":"P3","r":true}}'::jsonb
),
-- 8) BLS 210 (Gasses & Vapours filter, B-Lock, A1)
(
  'BLS 210',
  'Gasses & Vapours filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 210","it":"BLS 210"}'::jsonb,
  '{"en":"Gasses & Vapours filter with b-lock connection and activated carbons","it":"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['A1'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 1","gases":{"a":true}}}'::jsonb
),
-- 9) BLS 211 (Gasses & Vapours filter, B-Lock, A2)
(
  'BLS 211',
  'Gasses & Vapours filter with b-lock connection and activated carbons',
  'Filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Non deformable ABS filter canister avoids air corridors',
    'Excellent filtration performance with high-quality activated carbons'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 211","it":"BLS 211"}'::jsonb,
  '{"en":"Gasses & Vapours filter with b-lock connection and activated carbons","it":"Filtro per Gas & Vapori con attacco a baionetta b-lock e carboni attivi"}'::jsonb,
  '{"en":"Filters with b-lock connection.","it":"Filtro con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["ABS","Pleated glass fibre","Activated carbons grains"],"it":["ABS","fibra di vetro plissettata","granuli di carbone attivo"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Gasses & Vapours',
  array['A2'],
  null,
  '{"en14387":{"enabled":true,"class":"Class 2","gases":{"a":true}}}'::jsonb
);

commit;

-- Next batch to follow in subsequent commits (e.g. BLS 5700 and filters series)



-- Respirators seed inserts (batch 2 of N)
begin;

insert into public.products (
  name,
  description,
  short_description,
  category,
  sub_category,
  features,
  applications,
  industries,
  image_url,
  image2_url,
  out_of_stock,
  is_featured,
  order_priority,
  brands,
  tags_locales,
  name_locales,
  description_locales,
  short_description_locales,
  category_locales,
  sub_category_locales,
  size_locales,
  materials_locales,
  ce_category,
  published,
  related_product_id_1,
  related_product_id_2,
  related_product_id_3,
  related_product_id_4,
  protection_class,
  npf,
  connections,
  compatible_with,
  filter_type,
  protection_codes,
  ean,
  respiratory_standards
) values
-- 4) BLS 5700 (Full-face mask, B-Lock)
(
  'BLS 5700',
  'Full-face masks with silicone face seal and B-lock bayonet connection. Compatible with the BLS 200 filter range, for protection against gases/vapors and toxic particulates',
  'Full-face mask with b-lock connection',
  'Respiratory protection',
  'Full face masks',
  array[
    'Scratch resistant visor (Live visor), optical class 1 (EN166)',
    'Wide range of spare parts to extend use and lifespan of the mask',
    '6-point harness for precise adjustment and pressure distribution on the face',
    'Anallergic',
    'Silicone face seal for added comfort',
    'Available in three sizes',
    'Anti-fog visor',
    'Transmission of vocal sound with aluminium layer inside the breathing unit'
  ],
  array[
    'Protection against aerial contaminants and particles combined with eye protection',
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":["full-face mask","B-Lock"],"it":["maschera intera facciale","B-lock"]}'::jsonb,
  '{"en":"BLS 5700","it":"BLS 5700"}'::jsonb,
  '{"en":"Full-face masks with silicone face seal and B-lock bayonet connection. Compatible with the BLS 200 filter range, for protection against gases/vapors and toxic particulates","it":"Maschere intera con guarnizione facciale in silicone e raccordo a baionetta b-lock. Compatibili con la gamma di filtri BLS 200, per protezione da gas/vapori e particolati tossici"}'::jsonb,
  '{"en":"Full-face mask with b-lock connection","it":"Maschera intera facciale con connessione a baionetta b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Full face masks","it":"Maschere integrali"}'::jsonb,
  '{"en":"Universal","it":"Unica"}'::jsonb,
  '{"en":["Silicone","Polycarbonate (PC)","Other"],"it":["Silicone","Policarbonato (PC)","Altro"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  'Class 2',
  '1000 (Dust), 2000 (Gas filters)',
  array['B-Lock'],
  array['BLS 200 Filters','BLS 201 Filters'],
  null,
  null,
  '8001036',
  '{"en166":{"enabled":true,"class":"1"},"en136":{"enabled":true,"class":"Class 2"}}'::jsonb
),
-- 5) BLS 201-3 (Flat filter, B-Lock)
(
  'BLS 201-3',
  'Flat filters with b-lock connection. FFP3 R classified, protect from dusts, fibers, fumes, aerosols of toxic particles',
  'Flat filters with b-lock connection',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Lightweight and small size with slim profile',
    'Dust filtering efficiency 99.99%'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 201-3","it":"BLS 201-3"}'::jsonb,
  '{"en":"Flat filters with b-lock connection. FFP3 R classified, protect from dusts, fibers, fumes, aerosols of toxic particles","it":"Filtri piatti con attacco a baionetta b-lock. Classificazione FFP3 R, proteggono da polveri, fibre, fumi e aerosol di particelle tossiche"}'::jsonb,
  '{"en":"Flat filters with b-lock connection","it":"Filtro piatto con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["Polypropylene (PP)"],"it":["Polipropilene (PP)"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Dust',
  array['P3 R'],
  '8011218',
  '{"en143":{"enabled":true,"class":"P3","r":true}}'::jsonb
),
-- 6) BLS 201-3C (Flat filter, B-Lock, carbon)
(
  'BLS 201-3C',
  'Flat filters with b-lock connection. FFP3 R classified, protect from dusts, fibers, fumes, aerosols of toxic particles. Activated carbons to block gasses & vapour organic and acid in lower concentration than the TLV',
  'Flat filters with b-lock connection.',
  'Respiratory protection',
  'Filters, Cartidges and accessories',
  array[
    'Lightweight and small size with slim profile',
    'Dust filtering efficiency 99.99%'
  ],
  array[
    'Application depends on the filter used (gas, vapor, particulate, combined, etc.)'
  ],
  array['Chemical manufacturing','paint/spraying','metal working','welding','pharma'],
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%201.jpg',
  'https://bsrdkfjapuvbzultcela.supabase.co/storage/v1/object/public/products/02%202.jpg',
  false,
  false,
  0,
  array['BLS'],
  '{"en":[],"it":[]}'::jsonb,
  '{"en":"BLS 201-3C","it":"BLS 201-3C"}'::jsonb,
  '{"en":"Flat filters with b-lock connection. FFP3 R classified, protect from dusts, fibers, fumes, aerosols of toxic particles. Activated carbons to block gasses & vapour organic and acid in lower concentration than the TLV","it":"Filtri piatti con attacco a baionetta b-lock. Classificazione FFP3 R, proteggono da polveri, fibre, fumi e aerosol di particelle tossiche"}'::jsonb,
  '{"en":"Flat filters with b-lock connection.","it":"Filtro piatto con aggancio b-lock"}'::jsonb,
  '{"en":"Respiratory protection","it":"Protezione vie respiratorie"}'::jsonb,
  '{"en":"Filters, Cartidges and accessories","it":"Filtri, cartucce e accessori"}'::jsonb,
  null,
  '{"en":["Polypropylene (PP)","Polyester (PES) + carbon grains"],"it":["Polipropilene (PP)","Poliestere (PES) + granuli di carbone"]}'::jsonb,
  'III',
  true,
  'b4828268-dbab-4c9f-a5ea-524492f27480',
  'a18d1e82-6196-4266-8a67-f93dfaaea43d',
  '4078ffef-7c99-4538-b628-0b2c191db73a',
  'e85c4e38-5c51-41a8-b45e-a82baa2e2041',
  null,
  null,
  array['B-Lock'],
  array['Half masks','Full masks'],
  'Dust',
  array['P3 R'],
  '8011219',
  '{"en143":{"enabled":true,"class":"P3","r":true}}'::jsonb
);

commit;
