-- Careers locale merge from docs/LanguageAddon/Translations/Careers.csv
-- Data-only UPDATE. No ALTER TABLE. No is_published changes.
-- Run in the Supabase SQL editor when ready. Do not run blindly against production without a backup.
-- Merges en/it/fr/de/es keys into existing JSONB locale objects.
-- Blank CSV cells are skipped so existing database values stay.
-- Warning: the admin careers editor still saves only en/it. Saving a role there will wipe fr/de/es until that editor is extended.

BEGIN;

-- area-sales-manager-uk-northern-europe
UPDATE careers
SET title_locales = COALESCE(title_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Area Sales Manager (UK & Northern Europe)"'::jsonb,
    'it', '"Area Sales Manager (UK & Northern Europe)"'::jsonb,
    'fr', '"Area Sales Manager (Royaume-Uni et Europe du Nord)"'::jsonb,
    'de', '"Area Sales Manager (Vereinigtes Königreich und Nordeuropa)"'::jsonb,
    'es', '"Area Sales Manager (Reino Unido y Norte de Europa)"'::jsonb
  ),
  department_locales = COALESCE(department_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Sales"'::jsonb,
    'it', '"Commerciale"'::jsonb,
    'fr', '"Commercial"'::jsonb,
    'de', '"Vertrieb"'::jsonb,
    'es', '"Comercial"'::jsonb
  ),
  location_locales = COALESCE(location_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"London, UK"'::jsonb,
    'it', '"London, UK"'::jsonb,
    'fr', '"Londres, Royaume-Uni"'::jsonb,
    'de', '"London, Vereinigtes Königreich"'::jsonb,
    'es', '"Londres, Reino Unido"'::jsonb
  ),
  job_type_locales = COALESCE(job_type_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Full-time"'::jsonb,
    'it', '"Full-time"'::jsonb,
    'fr', '"Temps plein"'::jsonb,
    'de', '"Vollzeit"'::jsonb,
    'es', '"Tiempo completo"'::jsonb
  ),
  summary_locales = COALESCE(summary_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"We are seeking an ambitious and results-driven Area Sales Manager to lead our commercial growth in the United Kingdom and selected Northern European markets."'::jsonb,
    'it', '"Stiamo cercando un/una Area Sales Manager ambizioso/a e orientato/a ai risultati per guidare la nostra crescita commerciale nel Regno Unito e in alcuni mercati selezionati dell’Europa settentrionale."'::jsonb,
    'fr', '"Nous recherchons un(e) Area Sales Manager ambitieux(se) et orienté(e) résultats pour piloter notre croissance commerciale au Royaume-Uni et sur certains marchés sélectionnés d''Europe du Nord."'::jsonb,
    'de', '"Wir suchen einen ambitionierten und ergebnisorientierten Area Sales Manager (m/w/d) zur Steuerung unseres Geschäftswachstums im Vereinigten Königreich und in ausgewählten Märkten Nordeuropas."'::jsonb,
    'es', '"Buscamos un/a Area Sales Manager ambicioso/a y orientado/a a resultados para impulsar nuestro crecimiento comercial en el Reino Unido y en algunos mercados seleccionados del norte de Europa."'::jsonb
  ),
  description_locales = COALESCE(description_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"We are seeking an ambitious and results-driven Area Sales Manager to lead our commercial growth in the United Kingdom and selected Northern European markets.\n\nThe role has a dual focus:\n1. Driving growth in the UK market through new customer acquisition and account management.\n2. Supporting expansion into Northern Europe (Nordics, Benelux, Germany), identifying and developing new business opportunities while managing strategic accounts."'::jsonb,
    'it', '"Stiamo cercando un/una Area Sales Manager ambizioso/a e orientato/a ai risultati per guidare la nostra crescita commerciale nel Regno Unito e in alcuni mercati selezionati dell’Europa settentrionale.\n\nIl ruolo ha un duplice focus:\n1. Sviluppare la crescita nel mercato britannico attraverso l’acquisizione di nuovi clienti e la gestione degli account esistenti.\n2. Supportare l’espansione in Europa settentrionale (Nordics, Benelux, Germania), identificando e sviluppando nuove opportunità di business e gestendo account strategici."'::jsonb,
    'fr', '"Nous recherchons un(e) Area Sales Manager ambitieux(se) et orienté(e) résultats pour piloter notre croissance commerciale au Royaume-Uni et sur certains marchés sélectionnés d''Europe du Nord.\n\nLe poste a une double orientation :\n1. Développer la croissance sur le marché britannique grâce à l''acquisition de nouveaux clients et à la gestion des comptes existants.\n2. Soutenir l''expansion en Europe du Nord (pays nordiques, Benelux, Allemagne), en identifiant et en développant de nouvelles opportunités commerciales et en gérant des comptes stratégiques."'::jsonb,
    'de', '"Wir suchen einen ambitionierten und ergebnisorientierten Area Sales Manager (m/w/d) zur Steuerung unseres Geschäftswachstums im Vereinigten Königreich und in ausgewählten Märkten Nordeuropas.\n\nDie Rolle hat zwei Schwerpunkte:\n1. Förderung des Wachstums auf dem britischen Markt durch die Gewinnung neuer Kunden und die Betreuung bestehender Accounts.\n2. Unterstützung der Expansion in Nordeuropa (Nordics, Benelux, Deutschland) durch das Erkennen und Entwickeln neuer Geschäftsmöglichkeiten sowie die Betreuung strategischer Kunden."'::jsonb,
    'es', '"Buscamos un/a Area Sales Manager ambicioso/a y orientado/a a resultados para impulsar nuestro crecimiento comercial en el Reino Unido y en algunos mercados seleccionados del norte de Europa.\n\nEl puesto tiene un doble enfoque:\n1. Desarrollar el crecimiento en el mercado británico mediante la captación de nuevos clientes y la gestión de las cuentas existentes.\n2. Apoyar la expansión en el norte de Europa (países nórdicos, Benelux, Alemania), identificando y desarrollando nuevas oportunidades de negocio y gestionando cuentas estratégicas."'::jsonb
  ),
  responsibilities_locales = COALESCE(responsibilities_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Build and grow strategic partnership with our existing customers, ensuring best-in-class service and support whilst meeting commercial growth targets.", "Identify and secure new customers in the UK as the primary market focus.", "Develop opportunities in Benelux and Nordic countries, expanding the company’s European footprint.", "Build a strong sales pipeline across industrial, construction, glass and steel sectors to meet and exceed targets..", "Be the expert and provide tailored PPE solutions, ensuring high levels of customer satisfaction and loyalty.", "Provide input to shape sales strategies and market entry plans.", "Represent Hand Line at trade shows, exhibitions, and customer events across the region.", "Drive the expansion of our distribution segment by establishing strong relationships with our strategic partners and meeting sales quota on distribution.", "Work closely with Italian headquarters and cross-functional teams.", "Provide sales forecasts, market insights, and performance reports to management."]'::jsonb,
    'it', '["Costruire e sviluppare partnership strategiche con i clienti esistenti, garantendo un servizio e un supporto di livello eccellente, nel rispetto degli obiettivi di crescita commerciale.", "Individuare e acquisire nuovi clienti nel Regno Unito, che rappresenta il mercato principale di riferimento.", "Sviluppare opportunità nei Paesi del Benelux e nei Paesi Nordici, ampliando la presenza europea dell’azienda.", "Creare un solido pipeline commerciale nei settori industriale, edilizio, del vetro e dell’acciaio per raggiungere e superare i target prefissati.", "Essere un punto di riferimento esperto, fornendo soluzioni DPI personalizzate e garantendo elevati livelli di soddisfazione e fidelizzazione del cliente.", "Contribuire alla definizione delle strategie di vendita e dei piani di ingresso nei mercati.", "Rappresentare Hand Line in fiere, esposizioni ed eventi con i clienti in tutta la regione.", "Guidare l’espansione del segmento distributivo, costruendo relazioni solide con i partner strategici e raggiungendo gli obiettivi di vendita nella distribuzione.", "Collaborare strettamente con la sede centrale in Italia e con i team interfunzionali.", "Fornire forecast di vendita, analisi di mercato e report sulle performance al management."]'::jsonb,
    'fr', '["Construire et développer des partenariats stratégiques avec les clients existants, en garantissant un service et un support d''excellence, dans le respect des objectifs de croissance commerciale.", "Identifier et acquérir de nouveaux clients au Royaume-Uni, qui représente le marché de référence principal.", "Développer des opportunités dans les pays du Benelux et les pays nordiques, en élargissant la présence européenne de l''entreprise.", "Créer un pipeline commercial solide dans les secteurs industriel, du bâtiment, du verre et de l''acier afin d''atteindre et de dépasser les objectifs fixés.", "Être un point de référence expert, en fournissant des solutions EPI personnalisées et en garantissant des niveaux élevés de satisfaction et de fidélisation des clients.", "Contribuer à la définition des stratégies de vente et des plans d''entrée sur les marchés.", "Représenter Hand Line lors de salons, d''expositions et d''événements clients dans toute la région.", "Piloter l''expansion du segment de la distribution, en construisant des relations solides avec les partenaires stratégiques et en atteignant les objectifs de vente dans la distribution.", "Collaborer étroitement avec le siège central en Italie et avec les équipes interfonctionnelles.", "Fournir des prévisions de vente, des analyses de marché et des rapports de performance à la direction."]'::jsonb,
    'de', '["Aufbau und Entwicklung strategischer Partnerschaften mit bestehenden Kunden, wobei ein exzellentes Serviceniveau und exzellenter Support gewährleistet werden, unter Einhaltung der Ziele für das Geschäftswachstum.", "Identifizierung und Gewinnung neuer Kunden im Vereinigten Königreich, das den wichtigsten Referenzmarkt darstellt.", "Entwicklung von Geschäftsmöglichkeiten in den Benelux-Ländern und den nordischen Ländern zur Erweiterung der europäischen Präsenz des Unternehmens.", "Aufbau einer soliden Vertriebspipeline in den Bereichen Industrie, Bauwesen, Glas und Stahl, um die festgelegten Ziele zu erreichen und zu übertreffen.", "Fungieren als fachkundiger Ansprechpartner, indem maßgeschneiderte PSA-Lösungen bereitgestellt und ein hohes Maß an Kundenzufriedenheit und -bindung sichergestellt werden.", "Mitwirkung bei der Festlegung von Vertriebsstrategien und Markteintrittsplänen.", "Vertretung von Hand Line auf Messen, Ausstellungen und Kundenveranstaltungen in der gesamten Region.", "Den Ausbau des Vertriebssegments vorantreiben, indem solide Beziehungen zu strategischen Partnern aufgebaut und die Verkaufsziele im Vertrieb erreicht werden.", "Eng mit der Zentrale in Italien und mit funktionsübergreifenden Teams zusammenarbeiten.", "Verkaufsprognosen, Marktanalysen und Leistungsberichte an das Management liefern."]'::jsonb,
    'es', '["Construir y desarrollar alianzas estratégicas con los clientes existentes, garantizando un servicio y un soporte de excelente nivel, en línea con los objetivos de crecimiento comercial.", "Identificar y captar nuevos clientes en el Reino Unido, que representa el principal mercado de referencia.", "Desarrollar oportunidades en los países del Benelux y los países nórdicos, ampliando la presencia europea de la empresa.", "Crear un sólido pipeline comercial en los sectores industrial, de la construcción, del vidrio y del acero para alcanzar y superar los objetivos establecidos.", "Ser un referente experto, ofreciendo soluciones de EPI personalizadas y garantizando altos niveles de satisfacción y fidelización del cliente.", "Contribuir a la definición de las estrategias de venta y los planes de entrada en los mercados.", "Representar a Hand Line en ferias, exposiciones y eventos con clientes en toda la región.", "Liderar la expansión del segmento de distribución, construyendo relaciones sólidas con los socios estratégicos y alcanzando los objetivos de venta en la distribución.", "Colaborar estrechamente con la sede central en Italia y con los equipos interfuncionales.", "Proporcionar previsiones de ventas, análisis de mercado e informes de rendimiento a la dirección."]'::jsonb
  ),
  requirements_locales = COALESCE(requirements_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Strong track record in both account management and business development meeting and exceeding quarterly and yearly sales targets consistently.", "Excellent communication, negotiation, and presentation skills.", "Proven sales experience in PPE, safety equipment, or industrial products.", "Excellent communication, negotiation, and presentation skills.", "Complete fluency in English. Italian and other languages are a definite plus.", "Based in the UK, with frequent travel across the UK and Northern Europe.", "Self-motivated, entrepreneurial, and target-driven."]'::jsonb,
    'it', '["Comprovata esperienza sia nella gestione di account esistenti sia nello sviluppo di nuovo business, con risultati costanti nel raggiungimento e superamento dei target di vendita trimestrali e annuali.", "Eccellenti capacità di comunicazione, negoziazione e presentazione.", "Esperienza comprovata nelle vendite di DPI, attrezzature per la sicurezza o prodotti industriali.", "Ottima padronanza della lingua inglese; la conoscenza dell’italiano e di altre lingue costituisce un plus.", "Residenza nel Regno Unito, con disponibilità a frequenti viaggi all’interno del Regno Unito e nel Nord Europa.", "Spiccata motivazione personale, approccio imprenditoriale e forte orientamento agli obiettivi."]'::jsonb,
    'fr', '["Expérience avérée aussi bien dans la gestion de comptes existants que dans le développement de nouvelles affaires, avec des résultats constants dans l''atteinte et le dépassement des objectifs de vente trimestriels et annuels.", "Excellentes compétences en communication, négociation et présentation.", "Expérience avérée dans la vente d''EPI, d''équipements de sécurité ou de produits industriels.", "Excellente maîtrise de l''anglais ; la connaissance de l''italien et d''autres langues constitue un atout.", "Résidence au Royaume-Uni, avec disponibilité pour des déplacements fréquents au Royaume-Uni et en Europe du Nord.", "Forte motivation personnelle, approche entrepreneuriale et solide orientation vers les objectifs."]'::jsonb,
    'de', '["Nachgewiesene Erfahrung sowohl in der Betreuung bestehender Kunden als auch in der Entwicklung neuer Geschäfte, mit konstanten Ergebnissen beim Erreichen und Übertreffen der vierteljährlichen und jährlichen Verkaufsziele.", "Ausgezeichnete Kommunikations-, Verhandlungs- und Präsentationsfähigkeiten.", "Nachgewiesene Erfahrung im Verkauf von PSA, Sicherheitsausrüstung oder Industrieprodukten.", "Ausgezeichnete Englischkenntnisse; Kenntnisse der italienischen Sprache und weiterer Sprachen sind von Vorteil.", "Wohnsitz im Vereinigten Königreich, mit Bereitschaft zu häufigen Reisen innerhalb des Vereinigten Königreichs und in Nordeuropa.", "Ausgeprägte Eigenmotivation, unternehmerisches Denken und starke Zielorientierung."]'::jsonb,
    'es', '["Experiencia demostrada tanto en la gestión de cuentas existentes como en el desarrollo de nuevos negocios, con resultados constantes en el cumplimiento y la superación de los objetivos de venta trimestrales y anuales.", "Excelentes capacidades de comunicación, negociación y presentación.", "Experiencia demostrada en la venta de EPI, equipos de seguridad o productos industriales.", "Excelente dominio del inglés; el conocimiento del italiano y de otros idiomas constituye una ventaja.", "Residencia en el Reino Unido, con disponibilidad para viajar frecuentemente dentro del Reino Unido y en el norte de Europa.", "Marcada motivación personal, enfoque emprendedor y fuerte orientación a los objetivos."]'::jsonb
  ),
  benefits_locales = COALESCE(benefits_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Competitive salary with strong performance-related incentives.", "Strategically important role with significant growth opportunities.", "A central role in establishing and growing Hand Line’s presence in the UK and Northern Europe", "Strong benefits package.", "A dynamic, entrepreneurial company culture that values initiative and results."]'::jsonb,
    'it', '["Retribuzione competitiva con incentivi significativi legati alla performance.", "Ruolo strategicamente importante, con ampie opportunità di crescita professionale.", "Posizione centrale nello sviluppo e consolidamento della presenza di Hand Line nel Regno Unito e nel Nord Europa.", "Pacchetto di benefit competitivo.", "Cultura aziendale dinamica e imprenditoriale, che valorizza l’iniziativa e i risultati."]'::jsonb,
    'fr', '["Rémunération compétitive avec des primes significatives liées à la performance.", "Rôle stratégiquement important, offrant de vastes opportunités de croissance professionnelle.", "Position centrale dans le développement et la consolidation de la présence de Hand Line au Royaume-Uni et en Europe du Nord.", "Package d''avantages compétitif.", "Culture d''entreprise dynamique et entrepreneuriale, qui valorise l''initiative et les résultats."]'::jsonb,
    'de', '["Wettbewerbsfähige Vergütung mit erheblichen leistungsbezogenen Anreizen.", "Strategisch wichtige Position mit umfangreichen Möglichkeiten zur beruflichen Weiterentwicklung.", "Zentrale Position beim Ausbau und der Konsolidierung der Präsenz von Hand Line im Vereinigten Königreich und in Nordeuropa.", "Wettbewerbsfähiges Leistungspaket.", "Dynamische und unternehmerische Unternehmenskultur, die Eigeninitiative und Ergebnisse wertschätzt."]'::jsonb,
    'es', '["Retribución competitiva con incentivos significativos vinculados al rendimiento.", "Puesto estratégicamente importante, con amplias oportunidades de crecimiento profesional.", "Posición central en el desarrollo y la consolidación de la presencia de Hand Line en el Reino Unido y en el norte de Europa.", "Paquete de beneficios competitivo.", "Cultura empresarial dinámica y emprendedora, que valora la iniciativa y los resultados."]'::jsonb
  ),
  salary_range_locales = COALESCE(salary_range_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"£100,000 - £160,000 OTE"'::jsonb,
    'fr', '"£100,000 - £160,000 OTE"'::jsonb,
    'de', '"£100,000 - £160,000 OTE"'::jsonb,
    'es', '"£100,000 - £160,000 OTE"'::jsonb
  ),
  work_site_locales = COALESCE(work_site_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Hybrid. Travel > 50%"'::jsonb,
    'it', '"Ibrido. Viaggi > 50%"'::jsonb,
    'fr', '"Hybride. Déplacements > 50 %"'::jsonb,
    'de', '"Hybrid. Reisetätigkeit > 50 %"'::jsonb,
    'es', '"Híbrido. Viajes > 50 %"'::jsonb
  )
WHERE id = '97fa372d-6059-4bd6-886c-b5d7e6ebb375';

-- responsabile-magazzino-e-logistica
UPDATE careers
SET title_locales = COALESCE(title_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Responsabile Magazzino e Logistica"'::jsonb,
    'it', '"Responsabile Magazzino e Logistica"'::jsonb,
    'fr', '"Responsable Entrepôt et Logistique"'::jsonb,
    'de', '"Leiter Lager und Logistik"'::jsonb,
    'es', '"Responsable de Almacén y Logística"'::jsonb
  ),
  department_locales = COALESCE(department_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Operations"'::jsonb,
    'it', '"Logistica"'::jsonb,
    'fr', '"Logistique"'::jsonb,
    'de', '"Logistik"'::jsonb,
    'es', '"Logística"'::jsonb
  ),
  location_locales = COALESCE(location_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Canzo, Italy"'::jsonb,
    'it', '"Canzo, Italia"'::jsonb,
    'fr', '"Canzo, Italie"'::jsonb,
    'de', '"Canzo, Italien"'::jsonb,
    'es', '"Canzo, Italia"'::jsonb
  ),
  job_type_locales = COALESCE(job_type_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Full-time"'::jsonb,
    'it', '"Tempo pieno"'::jsonb,
    'fr', '"Temps plein"'::jsonb,
    'de', '"Vollzeit"'::jsonb,
    'es', '"Tiempo completo"'::jsonb
  ),
  summary_locales = COALESCE(summary_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Warehouse manager to drive the operations of our main distribution centre, ensuring efficient inventory management, order fulfilment, and logistical coordination for our industrial safety gloves products."'::jsonb,
    'it', '"Responsabile magazzino per gestire le operazioni del nostro centro di distribuzione, garantendo una gestione efficiente dell''inventario, l''evasione degli ordini e il coordinamento logistico per i nostri prodotti di guanti di sicurezza industriali."'::jsonb,
    'fr', '"Responsable d''entrepôt pour gérer les opérations de notre centre de distribution, en garantissant une gestion efficace des stocks, le traitement des commandes et la coordination logistique pour nos produits de gants de sécurité industriels."'::jsonb,
    'de', '"Lagerleiter zur Steuerung der Abläufe in unserem Distributionszentrum, mit dem Ziel einer effizienten Bestandsverwaltung, Auftragsabwicklung und logistischen Koordination für unsere industriellen Sicherheitshandschuhe."'::jsonb,
    'es', '"Responsable de almacén para gestionar las operaciones de nuestro centro de distribución, garantizando una gestión eficiente del inventario, la tramitación de pedidos y la coordinación logística de nuestros productos de guantes de seguridad industriales."'::jsonb
  ),
  description_locales = COALESCE(description_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"THIS ROLE IS BASED IN ITALY AND REQUIRES NATIVE/FLUENT ITALIAN.\n\nWe are looking for an experienced Warehouse Manager to oversee the operations of our main distribution center in Canzo, Italy. In this role, you will be responsible for ensuring efficient inventory management, accurate order fulfillment, and timely distribution of our safety equipment to customers across Europe.\n\nAs Warehouse Manager, you will also be responsible for optimizing warehouse layouts, implementing inventory control procedures, and maintaining high standards of safety and quality. You will work closely with our sales and production teams, as well as our logistics partners, to forecast demand, plan inventory levels, and ensure smooth operations throughout our supply chain.\n\nDo you have a proven track record in warehouse management and a commitment to operational excellence?\nAre you confident in implementing process improvements and leveraging technology to enhance warehouse efficiency?\nDo you want to help build a cohesive and high-performing team?\n\nIf so, you are the person we are looking for!"'::jsonb,
    'it', '"Cerchiamo un Responsabile di Magazzino esperto per supervisionare le operazioni del nostro centro di distribuzione principale a Canzo, Italia. In questo ruolo sarai responsabile di garantire una gestione efficiente dell''inventario, un''accurata evasione degli ordini e una distribuzione tempestiva dei nostri dispositivi di sicurezza a clienti in tutta Europa.\n\nCome Responsabile di Magazzino, sarai responsabile inoltre dell''ottimizzazione dei layout di magazzino, dell''implementazione di procedure di controllo dell''inventario e del mantenimento di elevati standard di sicurezza e qualità. Lavorerai a stretto contatto con i nostri team di vendita e produzione e con i nostri partner logistici per prevedere la domanda, pianificare i livelli di inventario e garantire operazioni fluide su tutta la nostra catena.\n\nHai una comprovata esperienza nella gestione di magazzino e un impegno per l''eccellenza operativa? \nSei a tuo agio nell''implementare miglioramenti di processo e sfruttare la tecnologia per migliorare l''efficienza del magazzino?\nVuoi contribuire a creare un team coeso e performante?\n\nSe si, sei la persona che cerchiamo!"'::jsonb,
    'fr', '"Nous recherchons un Responsable d''Entrepôt expérimenté pour superviser les opérations de notre centre de distribution principal à Canzo, en Italie. Dans ce rôle, vous serez responsable de garantir une gestion efficace des stocks, un traitement précis des commandes et une distribution rapide de nos équipements de sécurité auprès des clients dans toute l''Europe.\n\nEn tant que Responsable d''Entrepôt, vous serez également responsable de l''optimisation de l''agencement de l''entrepôt, de la mise en œuvre de procédures de contrôle des stocks et du maintien de normes élevées de sécurité et de qualité. Vous travaillerez en étroite collaboration avec nos équipes commerciales et de production ainsi qu''avec nos partenaires logistiques afin de prévoir la demande, planifier les niveaux de stock et garantir des opérations fluides tout au long de notre chaîne.\n\nAvez-vous une expérience avérée dans la gestion d''entrepôt et un engagement envers l''excellence opérationnelle ?\nÊtes-vous à l''aise pour mettre en œuvre des améliorations de processus et exploiter la technologie afin d''améliorer l''efficacité de l''entrepôt ?\nSouhaitez-vous contribuer à créer une équipe soudée et performante ?\n\nSi oui, vous êtes la personne que nous recherchons !"'::jsonb,
    'de', '"Wir suchen einen erfahrenen Lagerleiter (m/w/d), der die Abläufe unseres Hauptdistributionszentrums in Canzo, Italien, beaufsichtigt. In dieser Funktion sind Sie verantwortlich für eine effiziente Bestandsverwaltung, eine präzise Auftragsabwicklung und eine termingerechte Verteilung unserer Sicherheitsausrüstung an Kunden in ganz Europa.\n\nAls Lagerleiter sind Sie außerdem verantwortlich für die Optimierung der Lagerlayouts, die Einführung von Verfahren zur Bestandskontrolle sowie die Einhaltung hoher Sicherheits- und Qualitätsstandards. Sie arbeiten eng mit unseren Vertriebs- und Produktionsteams sowie mit unseren Logistikpartnern zusammen, um die Nachfrage vorherzusagen, die Bestandshöhen zu planen und einen reibungslosen Ablauf entlang unserer gesamten Kette zu gewährleisten.\n\nVerfügen Sie über nachgewiesene Erfahrung in der Lagerverwaltung und ein Engagement für operative Exzellenz?\nFühlen Sie sich wohl dabei, Prozessverbesserungen umzusetzen und Technologie zu nutzen, um die Effizienz des Lagers zu steigern?\nMöchten Sie dazu beitragen, ein geschlossenes und leistungsstarkes Team aufzubauen?\n\nWenn ja, dann sind Sie die Person, die wir suchen!"'::jsonb,
    'es', '"Buscamos un Responsable de Almacén con experiencia para supervisar las operaciones de nuestro centro de distribución principal en Canzo, Italia. En este puesto, serás responsable de garantizar una gestión eficiente del inventario, una preparación precisa de los pedidos y una distribución puntual de nuestros equipos de protección a clientes en toda Europa.\n\nComo Responsable de Almacén, también serás responsable de optimizar la distribución del almacén, implementar procedimientos de control de inventario y mantener altos estándares de seguridad y calidad. Trabajarás en estrecha colaboración con nuestros equipos de ventas y producción, así como con nuestros socios logísticos, para prever la demanda, planificar los niveles de inventario y garantizar operaciones fluidas en toda nuestra cadena.\n\n¿Tienes experiencia demostrada en la gestión de almacenes y un compromiso con la excelencia operativa?\n¿Te sientes cómodo implementando mejoras de proceso y aprovechando la tecnología para mejorar la eficiencia del almacén?\n¿Quieres contribuir a crear un equipo cohesionado y de alto rendimiento?\n\nSi es así, ¡eres la persona que buscamos!"'::jsonb
  ),
  responsibilities_locales = COALESCE(responsibilities_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Manage day-to-day warehouse operations, including receiving, storage, picking, packing, and shipping", "Implement and maintain inventory control procedures to ensure accuracy and minimize discrepancies", "Optimize warehouse layout and storage systems to maximize space utilization and operational efficiency", "Coordinate with logistics partners to ensure timely pickup and delivery of shipments", "Manage and improve warehouse management systems and technologies", "Collaborate with other departments to forecast demand and plan inventory levels", "Identify and implement process improvements to enhance efficiency and reduce costs"]'::jsonb,
    'it', '["Gestire le operazioni quotidiane di magazzino, inclusi ricevimento, stoccaggio, prelievo, imballaggio e spedizione", "Implementare e mantenere procedure di controllo dell''inventario per garantire accuratezza e minimizzare le discrepanze", "Ottimizzare il layout del magazzino e i sistemi di stoccaggio per massimizzare l''utilizzo dello spazio e l''efficienza operativa", "Coordinarsi con i partner logistici per garantire il ritiro e la consegna tempestivi delle spedizioni", "Gestire e migliorare i sistemi di gestione del magazzino e le tecnologie utilizzate", "Collaborare con altri dipartimenti per prevedere la domanda e pianificare i livelli di inventario", "Identificare e implementare miglioramenti dei processi per aumentare l''efficienza e ottimizzare i costi"]'::jsonb,
    'fr', '["Gérer les opérations quotidiennes de l''entrepôt, y compris la réception, le stockage, le prélèvement, l''emballage et l''expédition", "Mettre en œuvre et maintenir des procédures de contrôle des stocks afin de garantir l''exactitude et de minimiser les écarts", "Optimiser l''agencement de l''entrepôt et les systèmes de stockage afin de maximiser l''utilisation de l''espace et l''efficacité opérationnelle", "Se coordonner avec les partenaires logistiques pour garantir un enlèvement et une livraison rapides des expéditions", "Gérer et améliorer les systèmes de gestion d''entrepôt et les technologies utilisées", "Collaborer avec d''autres services pour prévoir la demande et planifier les niveaux de stocks", "Identifier et mettre en œuvre des améliorations de processus afin d''accroître l''efficacité et d''optimiser les coûts"]'::jsonb,
    'de', '["Die täglichen Lagerabläufe steuern, einschließlich Wareneingang, Lagerung, Kommissionierung, Verpackung und Versand", "Verfahren zur Bestandskontrolle implementieren und pflegen, um Genauigkeit sicherzustellen und Abweichungen zu minimieren", "Das Lagerlayout und die Lagersysteme optimieren, um die Raumnutzung und die betriebliche Effizienz zu maximieren", "Sich mit Logistikpartnern abstimmen, um die rechtzeitige Abholung und Zustellung von Sendungen sicherzustellen", "Die Lagerverwaltungssysteme und die eingesetzten Technologien verwalten und weiterentwickeln", "Mit anderen Abteilungen zusammenarbeiten, um die Nachfrage zu prognostizieren und die Bestandsniveaus zu planen", "Prozessverbesserungen identifizieren und umsetzen, um die Effizienz zu steigern und die Kosten zu optimieren"]'::jsonb,
    'es', '["Gestionar las operaciones diarias del almacén, incluyendo recepción, almacenamiento, preparación de pedidos, embalaje y envío", "Implementar y mantener procedimientos de control de inventario para garantizar la precisión y minimizar las discrepancias", "Optimizar la distribución del almacén y los sistemas de almacenamiento para maximizar el uso del espacio y la eficiencia operativa", "Coordinarse con los socios logísticos para garantizar la recogida y la entrega puntuales de los envíos", "Gestionar y mejorar los sistemas de gestión de almacén y las tecnologías utilizadas", "Colaborar con otros departamentos para prever la demanda y planificar los niveles de inventario", "Identificar e implementar mejoras de procesos para aumentar la eficiencia y optimizar los costes"]'::jsonb
  ),
  requirements_locales = COALESCE(requirements_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Italian language (native / bilingual / fully proficient), English highly desireable", "Minimum 5 years of warehouse management experience, preferably in manufacturing or distribution environments", "Proficiency with warehouse management systems and inventory control software", "Generation and management of documents (e.g. ddt) with software", "Excellent organizational, problem-solving, and communication skills", "Experience with forklift. License required, preferable if already possessed"]'::jsonb,
    'it', '["Lingua: Italiano richiesto, Inglese altamente preferibile", "Minimo 5 anni di esperienza nella gestione di magazzino, preferibilmente in ambienti di produzione o distribuzione", "Competenza con sistemi di gestione del magazzino e controllo dell''inventario", "Preparazione e gestione documenti di trasporto con software gestionale", "Eccellenti capacità organizzative, di risoluzione dei problemi e di comunicazione", "Esperienza con uso carrelli trasportatori / elevatori. Preferibile possesso patentino"]'::jsonb,
    'fr', '["Langue : italien requis, anglais fortement souhaité", "Minimum 5 ans d''expérience dans la gestion d''entrepôt, de préférence dans des environnements de production ou de distribution", "Maîtrise des systèmes de gestion d''entrepôt et de contrôle des stocks", "Préparation et gestion des documents de transport à l''aide de logiciels de gestion", "Excellentes capacités d''organisation, de résolution de problèmes et de communication", "Expérience dans l''utilisation de chariots élévateurs. Le permis de cariste est un plus"]'::jsonb,
    'de', '["Sprache: Italienisch erforderlich, Englisch stark bevorzugt", "Mindestens 5 Jahre Erfahrung in der Lagerverwaltung, vorzugsweise in Produktions- oder Distributionsumgebungen", "Kenntnisse in Lagerverwaltungssystemen und Bestandskontrolle", "Erstellung und Verwaltung von Transportdokumenten mithilfe von Verwaltungssoftware", "Ausgezeichnete organisatorische Fähigkeiten, Problemlösungskompetenz und Kommunikationsfähigkeiten", "Erfahrung im Umgang mit Gabelstaplern. Staplerschein von Vorteil"]'::jsonb,
    'es', '["Idioma: italiano requerido, inglés muy valorado", "Mínimo 5 años de experiencia en gestión de almacén, preferiblemente en entornos de producción o distribución", "Competencia con sistemas de gestión de almacén y control de inventario", "Preparación y gestión de documentos de transporte mediante software de gestión", "Excelentes capacidades de organización, resolución de problemas y comunicación", "Experiencia en el uso de carretillas elevadoras. Se valora positivamente el carné correspondiente"]'::jsonb
  ),
  benefits_locales = COALESCE(benefits_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Competitive salary based on experience", "Professional development opportunities"]'::jsonb,
    'it', '["Stipendio competitivo basato sull''esperienza", "Molte opportunità di sviluppo professionale", "Team dinamico e tante opportunita'' di contribuire attivamente alla strategia logistica"]'::jsonb,
    'fr', '["Salaire compétitif basé sur l''expérience", "De nombreuses opportunités de développement professionnel", "Équipe dynamique et de nombreuses opportunités de contribuer activement à la stratégie logistique"]'::jsonb,
    'de', '["Wettbewerbsfähiges Gehalt basierend auf Erfahrung", "Zahlreiche Möglichkeiten zur beruflichen Weiterentwicklung", "Dynamisches Team und zahlreiche Möglichkeiten, aktiv zur Logistikstrategie beizutragen"]'::jsonb,
    'es', '["Salario competitivo basado en la experiencia", "Numerosas oportunidades de desarrollo profesional", "Equipo dinámico y numerosas oportunidades de contribuir activamente a la estrategia logística"]'::jsonb
  ),
  work_site_locales = COALESCE(work_site_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"On-site only"'::jsonb,
    'it', '"Solo in sede"'::jsonb,
    'fr', '"Uniquement sur site"'::jsonb,
    'de', '"Nur vor Ort"'::jsonb,
    'es', '"Solo presencial"'::jsonb
  )
WHERE id = 'cc6d7a7b-3965-4460-a208-e9e65cf0bac3';

-- area-sales-manager
UPDATE careers
SET title_locales = COALESCE(title_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Area Sales Manager"'::jsonb,
    'it', '"Area Sales Manager"'::jsonb,
    'fr', '"Responsable des Ventes Régional"'::jsonb,
    'de', '"Gebietsverkaufsleiter"'::jsonb,
    'es', '"Gerente de Ventas de Zona"'::jsonb
  ),
  department_locales = COALESCE(department_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Sales"'::jsonb,
    'it', '"Commerciale"'::jsonb,
    'fr', '"Commercial"'::jsonb,
    'de', '"Vertrieb"'::jsonb,
    'es', '"Comercial"'::jsonb
  ),
  location_locales = COALESCE(location_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Canzo, Italy"'::jsonb,
    'it', '"Canzo, Italia"'::jsonb,
    'fr', '"Canzo, Italie"'::jsonb,
    'de', '"Canzo, Italien"'::jsonb,
    'es', '"Canzo, Italia"'::jsonb
  ),
  job_type_locales = COALESCE(job_type_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Full-time"'::jsonb,
    'it', '"Tempo pieno"'::jsonb,
    'fr', '"Temps plein"'::jsonb,
    'de', '"Vollzeit"'::jsonb,
    'es', '"Tiempo completo"'::jsonb
  ),
  summary_locales = COALESCE(summary_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Lead strategic and business development initiatives to expand Hand Line in Italy and across Europe. Develop new partnership opportunities and identify growth markets for our industrial safety solutions."'::jsonb,
    'it', '"Guidare iniziative strategiche e di sviluppo business per espandere Hand Line in Italia e Europa. Sviluppare nuove opportunità di partnership e identificare mercati di crescita per le nostre soluzioni di sicurezza industriali."'::jsonb,
    'fr', '"Piloter des initiatives stratégiques et de développement commercial pour étendre Hand Line en Italie et en Europe. Développer de nouvelles opportunités de partenariat et identifier des marchés de croissance pour nos solutions de sécurité industrielle."'::jsonb,
    'de', '"Strategische Initiativen und Geschäftsentwicklung vorantreiben, um Hand Line in Italien und Europa auszubauen. Neue Partnerschaftsmöglichkeiten entwickeln und Wachstumsmärkte für unsere industriellen Sicherheitslösungen identifizieren."'::jsonb,
    'es', '"Liderar iniciativas estratégicas y de desarrollo de negocio para expandir Hand Line en Italia y Europa. Desarrollar nuevas oportunidades de colaboración e identificar mercados de crecimiento para nuestras soluciones de seguridad industrial."'::jsonb
  ),
  description_locales = COALESCE(description_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"THIS ROLE IS BASED IN ITALY AND REQUIRES NATIVE/FULL PROFICIENCY ITALIAN.\n\nWe are looking for an ambitious and dynamic Area Sales Manager to drive growth and strengthen our presence in Italy and across continental Europe. This position combines the management and development of existing customers with the search for and acquisition of new business opportunities across various sectors.\n\nYou will be responsible for building long-term relationships, ensuring customer satisfaction, and achieving sales targets by identifying new opportunities both in Italy and abroad.\n\nThis role also has a strong strategic dimension: you will define and execute strategies to expand the company — including new product development, distribution channel growth, identification of new market segments and receptive industries, and more — while working closely with senior management.\n\nWe expect and offer strong prospects for growth into a leadership position."'::jsonb,
    'it', '"Ricerchiamo un/una Area Sales Manager ambizioso/a e dinamico/a per guidare la crescita e rafforzare la nostra presenza in Italia e in Europa continentale. La posizione combina la gestione e lo sviluppo dei clienti esistenti con la ricerca e acquisizione di nuove opportunità commerciali in diversi settori.\n\nSarai responsabile della costruzione di relazioni a lungo termine, della soddisfazione dei clienti e del raggiungimento degli obiettivi di vendita, individuando nuove opportunità sia in Italia che all’estero.\n\nQuesto ruolo ha anche una forte connotazione strategica; dovrai definire ed eseguire strategie per espandere l''azienda (sviluppo nuovi prodotti, sviluppo canali di distribuzione, identificazione di nuove categorie e settori ricettivi, etc.) e sarai a stretto contatto con il management.\nCi aspettiamo e vogliamo offrire forti prospettive di crescita in un ruolo dirigenziale."'::jsonb,
    'fr', '"Nous recherchons un(e) Area Sales Manager ambitieux(se) et dynamique pour piloter la croissance et renforcer notre présence en Italie et en Europe continentale. Le poste combine la gestion et le développement des clients existants avec la recherche et l''acquisition de nouvelles opportunités commerciales dans différents secteurs.\n\nVous serez responsable de la construction de relations à long terme, de la satisfaction des clients et de l''atteinte des objectifs de vente, en identifiant de nouvelles opportunités tant en Italie qu''à l''étranger.\n\nCe rôle revêt également une forte dimension stratégique ; vous devrez définir et mettre en œuvre des stratégies pour développer l''entreprise (développement de nouveaux produits, développement de canaux de distribution, identification de nouvelles catégories et secteurs réceptifs, etc.) et vous serez en contact étroit avec la direction.\nNous attendons et souhaitons offrir de solides perspectives de croissance vers un rôle de direction."'::jsonb,
    'de', '"Wir suchen einen ambitionierten und dynamischen Area Sales Manager (m/w/d), der das Wachstum vorantreibt und unsere Präsenz in Italien und im europäischen Festland stärkt. Die Position verbindet die Betreuung und Weiterentwicklung bestehender Kunden mit der Suche und Gewinnung neuer Geschäftsmöglichkeiten in verschiedenen Branchen.\n\nSie sind verantwortlich für den Aufbau langfristiger Beziehungen, die Kundenzufriedenheit und das Erreichen der Verkaufsziele, indem Sie neue Chancen sowohl in Italien als auch im Ausland identifizieren.\n\nDiese Rolle hat auch eine starke strategische Ausrichtung; Sie werden Strategien zur Expansion des Unternehmens definieren und umsetzen (Entwicklung neuer Produkte, Ausbau der Vertriebskanäle, Identifizierung neuer Kategorien und aufnahmefähiger Branchen usw.) und eng mit dem Management zusammenarbeiten.\nWir erwarten und bieten hervorragende Aufstiegschancen in eine Führungsrolle."'::jsonb,
    'es', '"Buscamos un/a Area Sales Manager ambicioso/a y dinámico/a para impulsar el crecimiento y reforzar nuestra presencia en Italia y en Europa continental. El puesto combina la gestión y el desarrollo de los clientes existentes con la búsqueda y captación de nuevas oportunidades comerciales en distintos sectores.\n\nSerás responsable de construir relaciones a largo plazo, de la satisfacción de los clientes y de alcanzar los objetivos de venta, identificando nuevas oportunidades tanto en Italia como en el extranjero.\n\nEste puesto tiene también una fuerte connotación estratégica; deberás definir y ejecutar estrategias para expandir la empresa (desarrollo de nuevos productos, desarrollo de canales de distribución, identificación de nuevas categorías y sectores receptivos, etc.) y estarás en estrecho contacto con la dirección.\nEsperamos y queremos ofrecer sólidas perspectivas de crecimiento hacia un puesto directivo."'::jsonb
  ),
  responsibilities_locales = COALESCE(responsibilities_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Manage and grow existing customer accounts in Italy, ensuring high satisfaction and retention.", "Identify upselling and cross-selling opportunities within the current portfolio.", "Act as a trusted advisor, providing product knowledge and regulatory guidance.", "Develop new business opportunities in Italy and continental Europe.", "Research markets, identify prospects, and build a robust sales pipeline to meet targets..", "Negotiate and close new contracts, ensuring alignment with company goals.", "Contribute to the sales strategy in alignment with company objectives.", "Provide regular sales forecasts, reports, and market intelligence to management."]'::jsonb,
    'it', '["Gestire e sviluppare i clienti esistenti in Italia, garantendo elevata soddisfazione e fidelizzazione.", "Individuare opportunità di upselling e cross-selling all’interno del portafoglio.", "Agire come consulente di fiducia, fornendo conoscenza dei prodotti e supporto normativo.", "Individuare e sviluppare nuove opportunità di business in Italia e in Europa continentale.", "Ricercare i mercati, identificare prospect e costruire un solido pipeline commerciale per eccedere i target..", "Negoziare e concludere nuovi contratti in linea con gli obiettivi aziendali.", "Contribuire alla definizione della strategia commerciale in linea con gli obiettivi aziendali.", "Fornire regolarmente forecast di vendita, report e analisi di mercato al management.", "Collaborare attivamente con i nostri partner strategici per crescere le attivita'' di distribuzione.", "Apertura di canali di distribuzione strategici"]'::jsonb,
    'fr', '["Gérer et développer les clients existants en Italie, en garantissant un haut niveau de satisfaction et de fidélisation.", "Identifier des opportunités d''upselling et de cross-selling au sein du portefeuille.", "Agir en tant que conseiller de confiance, en apportant une connaissance des produits et un accompagnement réglementaire.", "Identifier et développer de nouvelles opportunités commerciales en Italie et en Europe continentale.", "Étudier les marchés, identifier des prospects et construire un solide pipeline commercial afin de dépasser les objectifs.", "Négocier et conclure de nouveaux contrats conformément aux objectifs de l''entreprise.", "Contribuer à la définition de la stratégie commerciale en cohérence avec les objectifs de l''entreprise.", "Fournir régulièrement des prévisions de vente, des rapports et des analyses de marché à la direction.", "Collaborer activement avec nos partenaires stratégiques pour développer les activités de distribution.", "Ouverture de canaux de distribution stratégiques"]'::jsonb,
    'de', '["Bestehende Kunden in Italien betreuen und weiterentwickeln und dabei eine hohe Zufriedenheit und Kundenbindung sicherstellen.", "Upselling- und Cross-Selling-Möglichkeiten innerhalb des Portfolios identifizieren.", "Als vertrauenswürdiger Berater agieren und Produktwissen sowie Unterstützung in regulatorischen Fragen bereitstellen.", "Neue Geschäftsmöglichkeiten in Italien und im kontinentalen Europa identifizieren und entwickeln.", "Märkte recherchieren, Interessenten identifizieren und eine solide Vertriebspipeline aufbauen, um die Ziele zu übertreffen.", "Neue Verträge im Einklang mit den Unternehmenszielen verhandeln und abschließen.", "Zur Definition der Vertriebsstrategie im Einklang mit den Unternehmenszielen beitragen.", "Regelmäßig Verkaufsprognosen, Berichte und Marktanalysen an das Management liefern.", "Aktiv mit unseren strategischen Partnern zusammenarbeiten, um die Vertriebsaktivitäten auszubauen.", "Erschließung strategischer Vertriebskanäle"]'::jsonb,
    'es', '["Gestionar y desarrollar los clientes existentes en Italia, garantizando un alto nivel de satisfacción y fidelización.", "Identificar oportunidades de upselling y cross-selling dentro de la cartera.", "Actuar como asesor de confianza, aportando conocimiento de los productos y apoyo normativo.", "Identificar y desarrollar nuevas oportunidades de negocio en Italia y en Europa continental.", "Investigar los mercados, identificar prospectos y construir un sólido pipeline comercial para superar los objetivos.", "Negociar y cerrar nuevos contratos en línea con los objetivos de la empresa.", "Contribuir a la definición de la estrategia comercial en línea con los objetivos de la empresa.", "Proporcionar periódicamente previsiones de ventas, informes y análisis de mercado a la dirección.", "Colaborar activamente con nuestros socios estratégicos para hacer crecer las actividades de distribución.", "Apertura de canales de distribución estratégicos"]'::jsonb
  ),
  requirements_locales = COALESCE(requirements_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Proven track record in B2B sales, preferably within PPE, safety equipment, or industrial products.", "Strong experience in both account management and new business development.", "Excellent negotiation, presentation, and relationship-building skills.", "Fluency in Italian and English (other European languages are a plus).", "Willingness to travel frequently across Italy and continental Europe."]'::jsonb,
    'it', '["Esperienza comprovata nelle vendite B2B, preferibilmente in DPI, prodotti per la sicurezza o articoli industriali.", "Solida esperienza sia in gestione clienti che in sviluppo new business.", "Ottime capacità di negoziazione, presentazione e costruzione di relazioni.", "Fluente in italiano e inglese (altre lingue europee costituiranno un plus).", "Disponibilità a viaggiare frequentemente in Italia e in Europa continentale", "Orientamento ai risultati, autonomia e forte motivazione personale."]'::jsonb,
    'fr', '["Expérience avérée dans la vente B2B, de préférence dans les EPI, les produits de sécurité ou les articles industriels.", "Solide expérience à la fois dans la gestion de clients et dans le développement de nouvelles affaires.", "Excellentes compétences en négociation, présentation et création de relations.", "Maîtrise courante de l''italien et de l''anglais (d''autres langues européennes constitueront un atout).", "Disponibilité pour voyager fréquemment en Italie et en Europe continentale", "Orientation vers les résultats, autonomie et forte motivation personnelle."]'::jsonb,
    'de', '["Nachgewiesene Erfahrung im B2B-Vertrieb, vorzugsweise mit PSA, Sicherheitsprodukten oder Industrieartikeln.", "Fundierte Erfahrung sowohl in der Kundenbetreuung als auch in der Neukundengewinnung.", "Ausgezeichnete Fähigkeiten im Verhandeln, Präsentieren und im Aufbau von Beziehungen.", "Fließend in Italienisch und Englisch (weitere europäische Sprachen sind von Vorteil).", "Bereitschaft zu häufigen Reisen in Italien und im kontinentalen Europa", "Ergebnisorientierung, Selbstständigkeit und starke Eigenmotivation."]'::jsonb,
    'es', '["Experiencia demostrada en ventas B2B, preferiblemente en EPI, productos de seguridad o artículos industriales.", "Sólida experiencia tanto en gestión de clientes como en desarrollo de nuevos negocios.", "Excelentes capacidades de negociación, presentación y construcción de relaciones.", "Fluidez en italiano e inglés (otros idiomas europeos constituirán una ventaja).", "Disponibilidad para viajar frecuentemente por Italia y Europa continental", "Orientación a resultados, autonomía y fuerte motivación personal."]'::jsonb
  ),
  benefits_locales = COALESCE(benefits_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["Highly competitive salary with performance-based bonuses", "Opportunities for professional growth in international markets.", "Supportive and entrepreneurial work environment. We want to achieve and have a great time doing it!"]'::jsonb,
    'it', '["Retribuzione competitiva e sistema di forti incentivi legati alle performance.", "Un ruolo strategico in un’azienda internazionale in crescita, con solide radici in Italia.", "Opportunità di crescita professionale in mercati internazionali.", "Ambiente di lavoro dinamico, imprenditoriale e collaborativo."]'::jsonb,
    'fr', '["Rémunération compétitive et système de primes solides liées à la performance.", "Un rôle stratégique au sein d''une entreprise internationale en croissance, aux racines solides en Italie.", "Opportunités de croissance professionnelle sur les marchés internationaux.", "Environnement de travail dynamique, entrepreneurial et collaboratif."]'::jsonb,
    'de', '["Wettbewerbsfähige Vergütung und ein System starker leistungsbezogener Anreize.", "Eine strategische Rolle in einem wachsenden internationalen Unternehmen mit soliden Wurzeln in Italien.", "Möglichkeiten zur beruflichen Weiterentwicklung auf internationalen Märkten.", "Dynamisches, unternehmerisches und kooperatives Arbeitsumfeld."]'::jsonb,
    'es', '["Retribución competitiva y sistema de fuertes incentivos vinculados al rendimiento.", "Un papel estratégico en una empresa internacional en crecimiento, con sólidas raíces en Italia.", "Oportunidades de crecimiento profesional en mercados internacionales.", "Entorno de trabajo dinámico, emprendedor y colaborativo."]'::jsonb
  ),
  salary_range_locales = COALESCE(salary_range_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Base salary + Doubte OTE (100% bonus) + accelerators"'::jsonb,
    'it', '"RAL + 100% bonus + acceleratori"'::jsonb,
    'fr', '"Salaire brut annuel + 100 % de bonus + accélérateurs"'::jsonb,
    'de', '"Bruttojahresgehalt + 100 % Bonus + Beschleuniger"'::jsonb,
    'es', '"Salario bruto anual + 100 % de bonus + aceleradores"'::jsonb
  ),
  work_site_locales = COALESCE(work_site_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Office-based. Travel > 50%"'::jsonb,
    'it', '"In presenza. Viaggi > 50%"'::jsonb,
    'fr', '"En présentiel. Déplacements > 50 %"'::jsonb,
    'de', '"Vor Ort. Reisetätigkeit > 50 %"'::jsonb,
    'es', '"Presencial. Viajes > 50 %"'::jsonb
  )
WHERE id = '64179cef-60b0-473e-b756-b60f29b7f294';

COMMIT;
