-- EN resources locale merge
-- Source: docs/LanguageAddon/Translations/EnResources.csv
-- Data-only UPDATE. No ALTER TABLE. No published-flag changes.
-- Run in the Supabase SQL editor when ready. Take a backup first.
-- Merges en/it/fr/de/es into existing JSONB locale objects. Blank CSV cells are skipped.
-- Table: en_resources (legacy EN standards pages, integer ids).

BEGIN;

-- en_resources en-388-standard
UPDATE en_resources
SET title_locales = COALESCE(title_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"EN 388 Standard - Mechanical Protection"'::jsonb,
    'it', '"Normativa EN 388 - Protezione Meccanica"'::jsonb,
    'fr', '"Norme EN 388 - Protection mécanique"'::jsonb,
    'de', '"Norm EN 388 - Mechanischer Schutz"'::jsonb,
    'es', '"Norma EN 388 - Protección mecánica"'::jsonb
  ),
  summary_locales = COALESCE(summary_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"The EN 388:2016 standard represents the most sweeping revisions to this fundamental mechanical hand protection benchmark in over 13 years, with comprehensive performance measures for cut protection."'::jsonb,
    'it', '"La normativa EN 388:2016 rappresenta le revisioni più radicali a questo fondamentale punto di riferimento per la protezione meccanica delle mani in oltre 13 anni, con misure complete di prestazione per la protezione dai tagli."'::jsonb,
    'fr', '"La norme EN 388:2016 représente les révisions les plus radicales apportées à cette référence fondamentale en matière de protection mécanique des mains depuis plus de 13 ans, avec des mesures complètes de performance pour la protection contre les coupures."'::jsonb,
    'de', '"Die Norm EN 388:2016 stellt die grundlegendsten Überarbeitungen dieses zentralen Referenzstandards für den mechanischen Handschutz seit über 13 Jahren dar, mit umfassenden Leistungsmessungen für den Schnittschutz."'::jsonb,
    'es', '"La normativa EN 388:2016 representa las revisiones más radicales de esta referencia fundamental para la protección mecánica de las manos en más de 13 años, con medidas completas de rendimiento para la protección frente a cortes."'::jsonb
  ),
  content_locales = COALESCE(content_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"The EN 388:2016 standard represents the most sweeping revisions to this fundamental mechanical hand protection benchmark in over 13 years.\n\nThe new EN388 reports 5 or 6 separate mechanical performance measures, including two complementary scores for cut performance and the first ever test method for impact resistance applicable to mechanical protective gloves.\n\n## Performance Levels\n\nThe EN 388 standard measures protection against mechanical hazards and assigns performance levels for each test:\n\n1. **Abrasion Resistance** (0-4): Measured by the number of cycles required to abrade through the sample glove material.\n2. **Blade Cut Resistance** (0-5): Based on the number of cycles required to cut through the sample at a constant speed.\n3. **Tear Resistance** (0-4): The force needed to tear the sample material.\n4. **Puncture Resistance** (0-4): The force required to pierce the sample with a standard-sized point.\n5. **Cut Resistance - TDM Test** (A-F): Using the ISO 13997 method, measuring the force needed to cut through the material with a single movement.\n6. **Impact Protection** (P, F, or X): Where P indicates pass, F indicates fail, and X indicates the test wasn''t performed.\n\n## Marking System\n\nGloves certified to EN 388 are marked with a pictogram showing a shield along with a series of numbers and possibly letters that represent the performance levels achieved in each test. For example:\n\nEN 388: 4 5 4 3 C P\n\nThis would indicate:\n- Abrasion Resistance: Level 4\n- Blade Cut Resistance: Level 5\n- Tear Resistance: Level 4\n- Puncture Resistance: Level 3\n- Cut Resistance (TDM): Level C\n- Impact Protection: Pass\n\n## Significance\n\nUnderstanding these certification markings is critical for selecting the appropriate cut protection for specific industrial applications. Our HandLine cut-resistant gloves are engineered to meet or exceed the latest EN 388 standards, ensuring optimal protection for workers in high-risk environments while maintaining the dexterity necessary for precision tasks."'::jsonb,
    'it', '"La normativa EN 388:2016 rappresenta le revisioni più radicali a questo fondamentale punto di riferimento per la protezione meccanica delle mani in oltre 13 anni.\n\nLa nuova EN388 riporta 5 o 6 misure separate di prestazione meccanica, inclusi due punteggi complementari per la prestazione di taglio e il primo metodo di prova per la resistenza all''impatto applicabile ai guanti di protezione meccanica.\n\n## Livelli di Prestazione\n\nLa normativa EN 388 misura la protezione contro i rischi meccanici e assegna livelli di prestazione per ogni test:\n\n1. **Resistenza all''Abrasione** (0-4): Misurata dal numero di cicli necessari per abradersi attraverso il materiale del campione del guanto.\n2. **Resistenza al Taglio da Lama** (0-5): Basata sul numero di cicli necessari per tagliare il campione a velocità costante.\n3. **Resistenza allo Strappo** (0-4): La forza necessaria per strappare il materiale del campione.\n4. **Resistenza alla Perforazione** (0-4): La forza richiesta per perforare il campione con una punta di dimensioni standard.\n5. **Resistenza al Taglio - Test TDM** (A-F): Utilizzando il metodo ISO 13997, misurando la forza necessaria per tagliare il materiale con un singolo movimento.\n6. **Protezione dagli Impatti** (P, F o X): Dove P indica superato, F indica fallito e X indica che il test non è stato eseguito.\n\n## Sistema di Marcatura\n\nI guanti certificati EN 388 sono contrassegnati con un pittogramma che mostra uno scudo insieme a una serie di numeri e possibilmente lettere che rappresentano i livelli di prestazione raggiunti in ogni test. Per esempio:\n\nEN 388: 4 5 4 3 C P\n\nQuesto indicherebbe:\n- Resistenza all''Abrasione: Livello 4\n- Resistenza al Taglio da Lama: Livello 5\n- Resistenza allo Strappo: Livello 4\n- Resistenza alla Perforazione: Livello 3\n- Resistenza al Taglio (TDM): Livello C\n- Protezione dagli Impatti: Superato\n\n## Importanza\n\nComprendere questi marchi di certificazione è fondamentale per selezionare la protezione antitaglio appropriata per specifiche applicazioni industriali. I nostri guanti resistenti al taglio HandLine sono progettati per soddisfare o superare le ultime normative EN 388, garantendo una protezione ottimale per i lavoratori in ambienti ad alto rischio mantenendo la destrezza necessaria per compiti di precisione."'::jsonb,
    'fr', '"La norme EN 388:2016 représente les révisions les plus radicales de cette référence fondamentale pour la protection mécanique des mains depuis plus de 13 ans.\n\nLa nouvelle EN388 comporte 5 ou 6 mesures distinctes de performance mécanique, incluant deux scores complémentaires pour la performance de coupure et la première méthode d''essai pour la résistance à l''impact applicable aux gants de protection mécanique.\n\n## Niveaux de Performance\n\nLa norme EN 388 mesure la protection contre les risques mécaniques et attribue des niveaux de performance pour chaque test :\n\n1. **Résistance à l''Abrasion** (0-4) : Mesurée par le nombre de cycles nécessaires pour abraser le matériau de l''échantillon du gant.\n2. **Résistance à la Coupure par Lame** (0-5) : Basée sur le nombre de cycles nécessaires pour couper l''échantillon à vitesse constante.\n3. **Résistance à la Déchirure** (0-4) : La force nécessaire pour déchirer le matériau de l''échantillon.\n4. **Résistance à la Perforation** (0-4) : La force requise pour perforer l''échantillon avec une pointe de dimensions standard.\n5. **Résistance à la Coupure - Test TDM** (A-F) : Utilisant la méthode ISO 13997, mesurant la force nécessaire pour couper le matériau en un seul mouvement.\n6. **Protection contre les Chocs** (P, F ou X) : Où P indique réussi, F indique échoué et X indique que le test n''a pas été effectué.\n\n## Système de Marquage\n\nLes gants certifiés EN 388 sont marqués d''un pictogramme représentant un bouclier accompagné d''une série de chiffres et éventuellement de lettres représentant les niveaux de performance atteints à chaque test. Par exemple :\n\nEN 388 : 4 5 4 3 C P\n\nCela indiquerait :\n- Résistance à l''Abrasion : Niveau 4\n- Résistance à la Coupure par Lame : Niveau 5\n- Résistance à la Déchirure : Niveau 4\n- Résistance à la Perforation : Niveau 3\n- Résistance à la Coupure (TDM) : Niveau C\n- Protection contre les Chocs : Réussi\n\n## Importance\n\nComprendre ces marquages de certification est essentiel pour sélectionner la protection anticoupure appropriée pour des applications industrielles spécifiques. Nos gants anticoupure HandLine sont conçus pour répondre ou dépasser les dernières normes EN 388, garantissant une protection optimale pour les travailleurs dans des environnements à haut risque tout en conservant la dextérité nécessaire pour les tâches de précision."'::jsonb,
    'de', '"Die Norm EN 388:2016 stellt die radikalsten Überarbeitungen dieses grundlegenden Bezugspunkts für den mechanischen Handschutz seit über 13 Jahren dar.\n\nDie neue EN388 umfasst 5 oder 6 separate Messungen der mechanischen Leistung, einschließlich zweier ergänzender Werte für die Schnittleistung und der ersten Prüfmethode für die Stoßfestigkeit, die auf mechanische Schutzhandschuhe anwendbar ist.\n\n## Leistungsstufen\n\nDie Norm EN 388 misst den Schutz vor mechanischen Gefahren und vergibt für jeden Test Leistungsstufen:\n\n1. **Abriebfestigkeit** (0-4): Gemessen anhand der Anzahl der Zyklen, die erforderlich sind, um das Material der Handschuhprobe durchzuscheuern.\n2. **Schnittfestigkeit durch Klinge** (0-5): Basierend auf der Anzahl der Zyklen, die erforderlich sind, um die Probe bei konstanter Geschwindigkeit zu durchtrennen.\n3. **Weiterreißfestigkeit** (0-4): Die Kraft, die erforderlich ist, um das Material der Probe zu zerreißen.\n4. **Durchstichfestigkeit** (0-4): Die Kraft, die erforderlich ist, um die Probe mit einer Spitze von Standardgröße zu durchstechen.\n5. **Schnittfestigkeit - TDM-Test** (A-F): Unter Verwendung der Methode ISO 13997, wobei die Kraft gemessen wird, die erforderlich ist, um das Material mit einer einzigen Bewegung zu durchtrennen.\n6. **Schutz vor Stößen** (P, F oder X): Wobei P bestanden bedeutet, F nicht bestanden bedeutet und X bedeutet, dass der Test nicht durchgeführt wurde.\n\n## Kennzeichnungssystem\n\nHandschuhe, die nach EN 388 zertifiziert sind, werden mit einem Piktogramm gekennzeichnet, das einen Schild zusammen mit einer Reihe von Zahlen und möglicherweise Buchstaben zeigt, die die bei jedem Test erreichten Leistungsstufen darstellen. Zum Beispiel:\n\nEN 388: 4 5 4 3 C P\n\nDies würde Folgendes bedeuten:\n- Abriebfestigkeit: Stufe 4\n- Schnittfestigkeit durch Klinge: Stufe 5\n- Weiterreißfestigkeit: Stufe 4\n- Durchstichfestigkeit: Stufe 3\n- Schnittfestigkeit (TDM): Stufe C\n- Schutz vor Stößen: Bestanden\n\n## Bedeutung\n\nDas Verständnis dieser Zertifizierungskennzeichnungen ist entscheidend für die Auswahl des geeigneten Schnittschutzes für spezifische industrielle Anwendungen. Unsere HandLine Schnittschutzhandschuhe sind so konzipiert, dass sie die neuesten EN 388-Normen erfüllen oder übertreffen, und bieten Arbeitern in Umgebungen mit hohem Risiko optimalen Schutz, während die für Präzisionsaufgaben erforderliche Fingerfertigkeit erhalten bleibt."'::jsonb,
    'es', '"La norma EN 388:2016 representa las revisiones más radicales de este punto de referencia fundamental para la protección mecánica de las manos en más de 13 años.\n\nLa nueva EN388 incluye 5 o 6 medidas independientes de rendimiento mecánico, incluyendo dos puntuaciones complementarias para el rendimiento al corte y el primer método de prueba para la resistencia al impacto aplicable a los guantes de protección mecánica.\n\n## Niveles de Rendimiento\n\nLa norma EN 388 mide la protección contra riesgos mecánicos y asigna niveles de rendimiento para cada prueba:\n\n1. **Resistencia a la Abrasión** (0-4): Medida por el número de ciclos necesarios para desgastar el material de la muestra del guante.\n2. **Resistencia al Corte por Cuchilla** (0-5): Basada en el número de ciclos necesarios para cortar la muestra a velocidad constante.\n3. **Resistencia al Desgarro** (0-4): La fuerza necesaria para desgarrar el material de la muestra.\n4. **Resistencia a la Perforación** (0-4): La fuerza requerida para perforar la muestra con una punta de dimensiones estándar.\n5. **Resistencia al Corte - Prueba TDM** (A-F): Utilizando el método ISO 13997, midiendo la fuerza necesaria para cortar el material con un solo movimiento.\n6. **Protección contra Impactos** (P, F o X): Donde P indica superado, F indica fallido y X indica que la prueba no se realizó.\n\n## Sistema de Marcado\n\nLos guantes certificados EN 388 están marcados con un pictograma que muestra un escudo junto con una serie de números y posiblemente letras que representan los niveles de rendimiento alcanzados en cada prueba. Por ejemplo:\n\nEN 388: 4 5 4 3 C P\n\nEsto indicaría:\n- Resistencia a la Abrasión: Nivel 4\n- Resistencia al Corte por Cuchilla: Nivel 5\n- Resistencia al Desgarro: Nivel 4\n- Resistencia a la Perforación: Nivel 3\n- Resistencia al Corte (TDM): Nivel C\n- Protección contra Impactos: Superado\n\n## Importancia\n\nComprender estas marcas de certificación es fundamental para seleccionar la protección anticorte adecuada para aplicaciones industriales específicas. Nuestros guantes anticorte HandLine están diseñados para cumplir o superar las últimas normas EN 388, garantizando una protección óptima para los trabajadores en entornos de alto riesgo mientras se mantiene la destreza necesaria para tareas de precisión."'::jsonb
  ),
  category_locales = COALESCE(category_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Mechanical Protection"'::jsonb,
    'it', '"Protezione Meccanica"'::jsonb,
    'fr', '"Protection mécanique"'::jsonb,
    'de', '"Mechanischer Schutz"'::jsonb,
    'es', '"Protección mecánica"'::jsonb
  ),
  tags_locales = COALESCE(tags_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["EN 388", "cut protection", "mechanical hazards", "glove standards", "hand safety", "cut resistance"]'::jsonb,
    'it', '["EN 388", "protezione dai tagli", "rischi meccanici", "standard dei guanti", "sicurezza delle mani", "resistenza al taglio"]'::jsonb,
    'fr', '["EN 388", "protection contre les coupures", "risques mécaniques", "normes des gants", "sécurité des mains", "résistance à la coupure"]'::jsonb,
    'de', '["EN 388", "Schnittschutz", "mechanische Risiken", "Handschuhnormen", "Handsicherheit", "Schnittfestigkeit"]'::jsonb,
    'es', '["EN 388", "protección frente a cortes", "riesgos mecánicos", "normas de los guantes", "seguridad de las manos", "resistencia al corte"]'::jsonb
  )
WHERE id = 1;

-- en_resources en-407-standard
UPDATE en_resources
SET title_locales = COALESCE(title_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"EN 407 Standard - Thermal Protection"'::jsonb,
    'it', '"Normativa EN 407 - Protezione Termica"'::jsonb,
    'fr', '"Norme EN 407 - Protection thermique"'::jsonb,
    'de', '"Norm EN 407 - Hitzeschutz"'::jsonb,
    'es', '"Norma EN 407 - Protección térmica"'::jsonb
  ),
  summary_locales = COALESCE(summary_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"The use of suitable protective equipment is crucial when dealing with hot materials or other thermal hazards. The EN 407 was updated to provide enhanced assessment of PPE for hand protective equipment against thermal risks."'::jsonb,
    'it', '"L''uso di dispositivi di protezione adeguati è fondamentale quando si ha a che fare con materiali caldi o altri rischi termici. La EN 407 è stata aggiornata per fornire una valutazione avanzata dei DPI per dispositivi di protezione delle mani contro i rischi termici."'::jsonb,
    'fr', '"L''utilisation d''équipements de protection adaptés est essentielle lorsqu''il s''agit de matériaux chauds ou d''autres risques thermiques. La norme EN 407 a été mise à jour afin de fournir une évaluation avancée des EPI pour les dispositifs de protection des mains contre les risques thermiques."'::jsonb,
    'de', '"Der Einsatz geeigneter Schutzausrüstung ist unerlässlich im Umgang mit heißen Materialien oder anderen thermischen Gefahren. Die EN 407 wurde aktualisiert, um eine erweiterte PSA-Bewertung für Handschutzgeräte gegen thermische Risiken zu ermöglichen."'::jsonb,
    'es', '"El uso de equipos de protección adecuados es fundamental cuando se trabaja con materiales calientes u otros riesgos térmicos. La norma EN 407 se ha actualizado para proporcionar una evaluación avanzada de los EPI para dispositivos de protección de las manos frente a riesgos térmicos."'::jsonb
  ),
  content_locales = COALESCE(content_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"The use of suitable protective equipment is crucial when dealing with hot materials or other thermal hazards. Understanding the way these gloves are tested and rated will help you select the right gloves for your needs. Ansell provides you the tools to help you familiarise yourself with all there is to know about the latest regulatory updates. The EN 407 was updated and the PPE Regulation 2016/425 was recently established to provide enhanced assessment of PPE for hand protective equipment.\n\n## Performance Levels\n\nThe EN 407 standard measures protection against thermal risks and assigns performance levels for each test:\n\n1. **Burning Behavior** (0-4): Measures how long the material continues to burn and glow after the ignition source is removed.\n2. **Contact Heat** (0-4): Evaluates the temperature range at which the user will feel no pain for at least 15 seconds when the glove is in contact with a hot object.\n3. **Convective Heat** (0-4): Measures how long the glove can delay the transfer of heat from a flame.\n4. **Radiant Heat** (0-4): Indicates the time it takes for the glove to reach a certain temperature when exposed to radiant heat.\n5. **Small Splashes of Molten Metal** (0-4): Records the number of molten metal droplets required to heat the glove to a specific temperature.\n6. **Large Quantities of Molten Metal** (0-4): Measures the weight of molten metal needed to cause damage to a simulated skin placed behind the glove material.\n\n## Marking System\n\nGloves certified to EN 407 are marked with a pictogram showing a flame along with a series of six numbers that represent the performance levels achieved in each test. For example:\n\nEN 407: 4 3 2 1 4 2\n\nThis would indicate:\n- Burning Behavior: Level 4\n- Contact Heat: Level 3\n- Convective Heat: Level 2\n- Radiant Heat: Level 1\n- Small Splashes of Molten Metal: Level 4\n- Large Quantities of Molten Metal: Level 2\n\n## Significance\n\nThe EN 407 standard is critical for industries where workers are exposed to thermal hazards. HandLine''s heat-resistant gloves are engineered to provide optimal protection against various thermal risks while maintaining the dexterity and comfort necessary for precision work in high-temperature environments."'::jsonb,
    'it', '"L''uso di dispositivi di protezione adeguati è fondamentale quando si ha a che fare con materiali caldi o altri rischi termici. Comprendere il modo in cui questi guanti vengono testati e valutati ti aiuterà a selezionare i guanti giusti per le tue esigenze. Ansell ti fornisce gli strumenti per aiutarti a familiarizzare con tutto ciò che c''è da sapere sugli ultimi aggiornamenti normativi. La EN 407 è stata aggiornata e il Regolamento DPI 2016/425 è stato recentemente stabilito per fornire una valutazione avanzata dei DPI per dispositivi di protezione delle mani.\n\n## Livelli di Prestazione\n\nLa normativa EN 407 misura la protezione contro i rischi termici e assegna livelli di prestazione per ogni test:\n\n1. **Comportamento alla Fiamma** (0-4): Misura per quanto tempo il materiale continua a bruciare e a brillare dopo che la fonte di accensione viene rimossa.\n2. **Calore da Contatto** (0-4): Valuta l''intervallo di temperatura in cui l''utente non sentirà dolore per almeno 15 secondi quando il guanto è in contatto con un oggetto caldo.\n3. **Calore Convettivo** (0-4): Misura per quanto tempo il guanto può ritardare il trasferimento di calore da una fiamma.\n4. **Calore Radiante** (0-4): Indica il tempo necessario al guanto per raggiungere una certa temperatura quando esposto al calore radiante.\n5. **Piccoli Schizzi di Metallo Fuso** (0-4): Registra il numero di gocce di metallo fuso necessarie per riscaldare il guanto a una temperatura specifica.\n6. **Grandi Quantità di Metallo Fuso** (0-4): Misura il peso del metallo fuso necessario per causare danni a una pelle simulata posta dietro il materiale del guanto.\n\n## Sistema di Marcatura\n\nI guanti certificati EN 407 sono contrassegnati con un pittogramma che mostra una fiamma insieme a una serie di sei numeri che rappresentano i livelli di prestazione raggiunti in ogni test. Per esempio:\n\nEN 407: 4 3 2 1 4 2\n\nQuesto indicherebbe:\n- Comportamento alla Fiamma: Livello 4\n- Calore da Contatto: Livello 3\n- Calore Convettivo: Livello 2\n- Calore Radiante: Livello 1\n- Piccoli Schizzi di Metallo Fuso: Livello 4\n- Grandi Quantità di Metallo Fuso: Livello 2\n\n## Importanza\n\nLa normativa EN 407 è cruciale per le industrie in cui i lavoratori sono esposti a rischi termici. I guanti resistenti al calore di HandLine sono progettati per fornire una protezione ottimale contro vari rischi termici mantenendo la destrezza e il comfort necessari per lavori di precisione in ambienti ad alta temperatura."'::jsonb,
    'fr', '"L''utilisation d''équipements de protection adéquats est fondamentale lorsqu''il s''agit de matériaux chauds ou d''autres risques thermiques. Comprendre la façon dont ces gants sont testés et évalués vous aidera à sélectionner les gants adaptés à vos besoins. Ansell vous fournit les outils pour vous aider à vous familiariser avec tout ce qu''il faut savoir sur les dernières mises à jour normatives. La norme EN 407 a été mise à jour et le règlement EPI 2016/425 a récemment été établi pour fournir une évaluation avancée des EPI pour les dispositifs de protection des mains.\n\n## Niveaux de Performance\n\nLa norme EN 407 mesure la protection contre les risques thermiques et attribue des niveaux de performance pour chaque test :\n\n1. **Comportement à la Flamme** (0-4) : Mesure la durée pendant laquelle le matériau continue de brûler et de rougeoyer après le retrait de la source d''inflammation.\n2. **Chaleur de Contact** (0-4) : Évalue la plage de température dans laquelle l''utilisateur ne ressentira aucune douleur pendant au moins 15 secondes lorsque le gant est en contact avec un objet chaud.\n3. **Chaleur Convective** (0-4) : Mesure le temps pendant lequel le gant peut retarder le transfert de chaleur provenant d''une flamme.\n4. **Chaleur Radiante** (0-4) : Indique le temps nécessaire au gant pour atteindre une certaine température lorsqu''il est exposé à la chaleur radiante.\n5. **Petites Projections de Métal en Fusion** (0-4) : Enregistre le nombre de gouttes de métal en fusion nécessaires pour chauffer le gant à une température spécifique.\n6. **Grandes Quantités de Métal en Fusion** (0-4) : Mesure le poids de métal en fusion nécessaire pour causer des dommages à une peau simulée placée derrière le matériau du gant.\n\n## Système de Marquage\n\nLes gants certifiés EN 407 sont marqués d''un pictogramme représentant une flamme accompagnée d''une série de six chiffres représentant les niveaux de performance atteints pour chaque test. Par exemple :\n\nEN 407 : 4 3 2 1 4 2\n\nCela indiquerait :\n- Comportement à la Flamme : Niveau 4\n- Chaleur de Contact : Niveau 3\n- Chaleur Convective : Niveau 2\n- Chaleur Radiante : Niveau 1\n- Petites Projections de Métal en Fusion : Niveau 4\n- Grandes Quantités de Métal en Fusion : Niveau 2\n\n## Importance\n\nLa norme EN 407 est cruciale pour les industries dans lesquelles les travailleurs sont exposés à des risques thermiques. Les gants anti-chaleur de HandLine sont conçus pour offrir une protection optimale contre divers risques thermiques tout en conservant la dextérité et le confort nécessaires pour les travaux de précision dans des environnements à haute température."'::jsonb,
    'de', '"Der Einsatz geeigneter Schutzausrüstung ist von grundlegender Bedeutung im Umgang mit heißen Materialien oder anderen thermischen Gefahren. Zu verstehen, wie diese Handschuhe geprüft und bewertet werden, hilft Ihnen, die richtigen Handschuhe für Ihre Anforderungen auszuwählen. Ansell stellt Ihnen die Werkzeuge zur Verfügung, damit Sie sich mit allem vertraut machen können, was Sie über die neuesten normativen Aktualisierungen wissen müssen. Die EN 407 wurde aktualisiert, und die PSA-Verordnung 2016/425 wurde kürzlich eingeführt, um eine erweiterte Bewertung der PSA für Handschutzprodukte zu ermöglichen.\n\n## Leistungsstufen\n\nDie Norm EN 407 misst den Schutz gegen thermische Gefahren und vergibt für jeden Test Leistungsstufen:\n\n1. **Brennverhalten** (0-4): Misst, wie lange das Material nach Entfernen der Zündquelle weiterbrennt und weiterglüht.\n2. **Kontaktwärme** (0-4): Bewertet den Temperaturbereich, in dem der Träger mindestens 15 Sekunden lang keinen Schmerz empfindet, wenn der Handschuh mit einem heißen Gegenstand in Kontakt kommt.\n3. **Konvektionswärme** (0-4): Misst, wie lange der Handschuh die Wärmeübertragung von einer Flamme verzögern kann.\n4. **Strahlungswärme** (0-4): Gibt die Zeit an, die der Handschuh benötigt, um bei Einwirkung von Strahlungswärme eine bestimmte Temperatur zu erreichen.\n5. **Kleine Spritzer geschmolzenen Metalls** (0-4): Erfasst die Anzahl der Tropfen geschmolzenen Metalls, die erforderlich sind, um den Handschuh auf eine bestimmte Temperatur zu erwärmen.\n6. **Große Mengen geschmolzenen Metalls** (0-4): Misst das Gewicht des geschmolzenen Metalls, das erforderlich ist, um eine hinter dem Handschuhmaterial angebrachte simulierte Haut zu schädigen.\n\n## Kennzeichnungssystem\n\nNach EN 407 zertifizierte Handschuhe sind mit einem Piktogramm gekennzeichnet, das eine Flamme zusammen mit einer Reihe von sechs Zahlen zeigt, welche die in jedem Test erreichten Leistungsstufen darstellen. Zum Beispiel:\n\nEN 407: 4 3 2 1 4 2\n\nDies würde bedeuten:\n- Brennverhalten: Stufe 4\n- Kontaktwärme: Stufe 3\n- Konvektionswärme: Stufe 2\n- Strahlungswärme: Stufe 1\n- Kleine Spritzer geschmolzenen Metalls: Stufe 4\n- Große Mengen geschmolzenen Metalls: Stufe 2\n\n## Bedeutung\n\nDie Norm EN 407 ist für Branchen von entscheidender Bedeutung, in denen Arbeitnehmer thermischen Gefahren ausgesetzt sind. Die Hitzeschutzhandschuhe von HandLine sind so konzipiert, dass sie optimalen Schutz vor verschiedenen thermischen Gefahren bieten und dabei die für Präzisionsarbeiten in Hochtemperaturumgebungen erforderliche Fingerfertigkeit und den Tragekomfort bewahren."'::jsonb,
    'es', '"El uso de equipos de protección adecuados es fundamental cuando se trabaja con materiales calientes u otros riesgos térmicos. Comprender la forma en que estos guantes se prueban y evalúan te ayudará a seleccionar los guantes adecuados para tus necesidades. Ansell te proporciona las herramientas para ayudarte a familiarizarte con todo lo que hay que saber sobre las últimas actualizaciones normativas. La norma EN 407 se ha actualizado y el Reglamento EPI 2016/425 se ha establecido recientemente para proporcionar una evaluación avanzada de los EPI para dispositivos de protección de las manos.\n\n## Niveles de Prestación\n\nLa normativa EN 407 mide la protección contra los riesgos térmicos y asigna niveles de prestación para cada prueba:\n\n1. **Comportamiento a la Llama** (0-4): Mide durante cuánto tiempo el material continúa ardiendo y brillando después de retirar la fuente de ignición.\n2. **Calor de Contacto** (0-4): Evalúa el intervalo de temperatura en el que el usuario no sentirá dolor durante al menos 15 segundos cuando el guante esté en contacto con un objeto caliente.\n3. **Calor Convectivo** (0-4): Mide durante cuánto tiempo el guante puede retrasar la transferencia de calor procedente de una llama.\n4. **Calor Radiante** (0-4): Indica el tiempo necesario para que el guante alcance una determinada temperatura cuando se expone al calor radiante.\n5. **Pequeñas Salpicaduras de Metal Fundido** (0-4): Registra el número de gotas de metal fundido necesarias para calentar el guante hasta una temperatura específica.\n6. **Grandes Cantidades de Metal Fundido** (0-4): Mide el peso de metal fundido necesario para causar daños a una piel simulada colocada detrás del material del guante.\n\n## Sistema de Marcado\n\nLos guantes certificados según la norma EN 407 están marcados con un pictograma que muestra una llama junto con una serie de seis números que representan los niveles de prestación alcanzados en cada prueba. Por ejemplo:\n\nEN 407: 4 3 2 1 4 2\n\nEsto indicaría:\n- Comportamiento a la Llama: Nivel 4\n- Calor de Contacto: Nivel 3\n- Calor Convectivo: Nivel 2\n- Calor Radiante: Nivel 1\n- Pequeñas Salpicaduras de Metal Fundido: Nivel 4\n- Grandes Cantidades de Metal Fundido: Nivel 2\n\n## Importancia\n\nLa normativa EN 407 es crucial para las industrias en las que los trabajadores están expuestos a riesgos térmicos. Los guantes resistentes al calor de HandLine están diseñados para ofrecer una protección óptima frente a diversos riesgos térmicos, manteniendo la destreza y la comodidad necesarias para trabajos de precisión en entornos de alta temperatura."'::jsonb
  ),
  category_locales = COALESCE(category_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '"Thermal Protection"'::jsonb,
    'it', '"Protezione Termica"'::jsonb,
    'fr', '"Protection thermique"'::jsonb,
    'de', '"Hitzeschutz"'::jsonb,
    'es', '"Protección térmica"'::jsonb
  ),
  tags_locales = COALESCE(tags_locales, '{}'::jsonb) || jsonb_build_object(
    'en', '["EN 407", "heat protection", "thermal hazards", "glove standards", "hand safety", "heat resistance", "molten metal"]'::jsonb,
    'it', '["EN 407", "protezione termica", "rischi termici", "standard dei guanti", "sicurezza delle mani", "resistenza al calore", "metallo fuso"]'::jsonb,
    'fr', '["EN 407", "protection thermique", "risques thermiques", "normes des gants", "sécurité des mains", "résistance à la chaleur", "métal en fusion"]'::jsonb,
    'de', '["EN 407", "Hitzeschutz", "thermische Risiken", "Handschuhnormen", "Handsicherheit", "Hitzebeständigkeit", "geschmolzenes Metall"]'::jsonb,
    'es', '["EN 407", "protección térmica", "riesgos térmicos", "normas de los guantes", "seguridad de las manos", "resistencia al calor", "metal fundido"]'::jsonb
  )
WHERE id = 2;

COMMIT;
